### ISSUE TITLE
Personalized Property Onsite Capability Integration

### ISSUE THREAD

**Issue by krisnaBukitVista** [Bukit-Vista/roadmap#100]
# Description 
Currently, all properties in our system share a default set of onsite capabilities. However, we now have personalized onsite capability data for each property, allowing us to cater to property-specific needs more accurately. This project aims to integrate this personalized data into our system, ensuring that each property’s unique capabilities are utilized efficiently.

# Problem 
The existing system uses a one-size-fits-all approach to onsite capability, which does not accurately reflect each property's unique attributes. This leads to suboptimal recommendations and affects the quality of service. Our system’s default capability model lacks flexibility, resulting in a mismatch between guest requests and actual property capabilities.

# Solution 
To address this issue, we propose a hybrid data storage approach to integrate personalized onsite capability data:
- Structured Data Management with MySQL:
  - Utilize MySQL as the primary storage for structured data, ensuring easy management for frequent updates or additions. This provides a well-organized structure for property capability data, making it straightforward to maintain.

- Document-Based Storage for Fast Retrieval with ChromaDB:
  - For quick data retrieval, store each property’s capability data as a document in a vector database like ChromaDB. This allows efficient access to property-specific capabilities, particularly useful when interfacing with tools like Gaia.

Recommendation:
- Align this project with similar initiatives, such as David's AI project, focusing on knowledge base creation and tool improvement.
- Split the project into multiple subtasks for clarity:
  - Develop Property Capability Knowledge Base
  - Enhance Existing Tool for Knowledge Base Integration

# Measurement Metrics
- System Accuracy: Measure the accuracy of onsite capabilities provided to guests based on personalized data

# SLA
- System Accuracy: Measure the accuracy of onsite capabilities aiming for a 95% match rate with property capabilities.

# Evaluation 
The knowledge manager has successfully compiled and structured a comprehensive knowledge base to equip staff with the required capabilities to effectively serve guests. This process has ensured that all relevant information, protocols, and best practices are readily accessible to enhance service quality.

The newly developed knowledge framework has been seamlessly integrated into our current Knowledge Management System, ensuring consistency and ease of access for staff across all operational levels.

To validate the effectiveness of this integration, an internal testing phase was conducted utilizing 15 representative samples. These tests assessed system functionality, usability, and accuracy of the knowledge base. The integration has passed all testing criteria, confirming its readiness for deployment.

This accomplishment reinforces our commitment to operational excellence and guest satisfaction.

**Comment by Vidiskiu** [comment]
Prepare Second Iteration to include Data Entry

**Comment by krisnaBukitVista** [comment]
Evaluation Report

Since the system was implemented just two days ago, we have already collected 20 sample interactions. While this is a promising start, it has highlighted certain limitations in GAIA's current capability.

1. Capacity Coverage: GAIA seems to reject obvious requests because our capacity data does not yet cover all possible types of guest requests. This indicates room for improvement in the training data and logic coverage.
2. Reliability Assessment: Out of the 20 samples collected, GAIA successfully recognized and processed 12 requests as intended. However, 8 requests, despite being within its intended scope, were not recognized as valid requests for onsite staff. This results in a current reliability rate of 60% (12 recognized out of 20 total requests).
3. Further Analysis:
  * If you wish to review all the collected samples, you can access the full dataset in the provided spreadsheet https://docs.google.com/spreadsheets/d/162QEdifReEkEMex-fhvcEItpXg3j1sJwizDpqlM53BU/edit?usp=sharing
  * For a focused view of problematic cases, you can use the 

following MySQL query to extract relevant data for analysis:
```
SELECT process_category_id, arguments, message, created_at
FROM hermes_process_category_tool_logs
WHERE process_category_id IN (105158, 105145, 105103, 104958, 104897, 104672, 104666, 104391);
```

**Comment by Vidiskiu** [comment]
Overall Point: 5.75
Functional Complexity: 1.75

> Integrating personalized data for property-specific onsite capabilities introduces a moderate to high level of functional complexity due to the need for different data management approaches for structured and unstructured data, and the alignment with other initiatives like the knowledge base project.

Technical Complexity: 2

> The technical aspect is quite high due to the need for a hybrid data storage system with MySQL and ChromaDB, requiring knowledge of both relational and vector database management, and ensuring efficient data retrieval and updates.

UI/UX Complexity and Impact: 0.5

> Since the issue description does not explicitly mention UI/UX changes, it is assumed that the impact here is minor, with potential updates to internal knowledge management tools rather than any external user-facing interfaces.

Testing and Quality Assurance: 1

> The project will require thorough testing to ensure system accuracy against the SLA of a 95% match rate with property capabilities, indicating a moderate to high level of testing complexity.

Risk and Dependencies: 0.5

> The risk appears to be moderate given the dependencies on external data sources and the integration with other projects like the AI knowledge base, though there's an indication of clear planning to mitigate risks with structured subtasks.
