### ISSUE TITLE
Pricing Page Enhancement

### ISSUE THREAD

**Issue by krisnaBukitVista** [Bukit-Vista/roadmap#104]
# Description 
This project aims to enhance the pricing page on our website to improve user experience, increase engagement, and ensure ease of content updates. The Marketing team has requested several improvements, including a fresh design, an additional pricing plan option, rewritten content, and the capability for dynamic content modification.

# Problem 
The current pricing page lacks visual appeal and flexibility. It provides limited pricing options, which may not adequately address all user needs. Additionally, the static content setup makes it challenging for users to modify content directly, impacting our ability to keep information current and relevant.

# Solution 
- Fresh Design: Implement a new, visually engaging design for the pricing page layout to improve aesthetics and user experience.
- Additional Pricing Option: Add a fourth pricing plan option, with the following categories:
  - Delightful Property
  - Inspired Branding
  - Inspired Investment
  - Enterprise Investment Strategy
- Content Rewrite: Update and rewrite the pricing page content to better communicate each plan’s benefits, align with our brand, and improve readability.
- Dynamic Content Capability: Ensure the content can be dynamically modified, enabling users to update information directly without needing technical assistance.

# Measurement metrics
- Average Session Duration: Track the time users spend on the pricing page to assess engagement improvements.
- Bounce Rate: Monitor bounce rates to measure how effectively the new design and content retain user interest.
- Click event count: Monitor how many user interested to see the pricing packages by clicking "get started"

# SLA 
- Engagement Metrics: Achieve a 10% increase in average session duration and click count. A 10% decrease in bounce rate within one month post-implementation.

# Evaluation 
![Image](https://github.com/user-attachments/assets/504e7224-0e90-48bc-a69b-7d4c7ed911ef)

## User Feedback:
The user provided minor feedback, such as rewriting content and changing icons. These updates have been completed, and the user has fully approved the project.

## Analytics Comparison (Nov 26 - Dec 1 vs. Nov 20 - Nov 25):
- Average Engagement Time per Active User:
  - Before: 1m 26s
  - After: 1m 18s
  - % Change: -18%

- Average Session Duration:
  - Before: 5m 28s
  - After: 4m 23s
  - % Change: -20%

- Number of Clicks (Get Started CTA):
  - Before: 2
  - After: 19
  - % Change: +850%

## Analysis:
- The data indicates a decrease in session duration and engagement time, suggesting users spend less time interacting with the page.
- However, the significant increase in "Get Started" CTA clicks (+850%) suggests users are more inclined to take action on the pricing page.
- This reflects an improvement in converting user intent, even with reduced overall engagement time.

**Comment by Vidiskiu** [comment]
Final evaluation scheduled on 2024-12-01

**Comment by Vidiskiu** [comment]
Overall Point: 4.75
Functional Complexity: 0.75

> The functional complexity is moderate due to new pricing options and the capability for dynamic content, but since it is an enhancement of existing features, it is not highly complex.

Technical Complexity: 1.5

> Technically, adding dynamic content capabilities and a new pricing plan involves moderate to significant changes to the existing system. However, it does not seem to require architectural changes or new technologies.

UI/UX Complexity and Impact: 1.25

> Significant UI/UX changes are expected with a fresh design and additional pricing plan options, which means it's a high UI/UX complexity task.

Testing and Quality Assurance: 0.75

> Testing will include verifying new designs, content rewrite, and dynamic content functionality. It requires moderate effort, but extensive testing might not be necessary because the risk of functionality failure seems low.

Risk and Dependencies: 0.5

> There is moderate risk in terms of ensuring that the new pricing options and dynamic content don't disrupt current operations. However, there is minor feedback and positive user approval, which reduces the overall risk.
