### ISSUE TITLE
Integrating full board report to AION

### ISSUE THREAD

**Issue by krisnaBukitVista** [Bukit-Vista/roadmap#108]
# Description 
To improve efficiency and enhance the BVGO app's functionality, we aim to automate the creation and distribution of full board reports for 46 properties via AION. This initiative will reduce manual workload for community managers and increase app engagement by utilizing AION's content creation and distribution capabilities.

# Problem 
- Currently, community managers manually email full board reports to 46 properties at the beginning of every month, which is time-intensive and prone to errors.
- Each property’s report includes a unique Coda document link for its monthly performance review.
- Manual processing limits scalability and decreases efficiency in report distribution.

# Solution 
- Automate Report Creation:
  - Use AION to generate standardized full board reports.
  - Integrate existing templates into AION’s content creation system to ensure consistency.

- Automate Distribution:
  - Leverage AION's action feature (currently known as "Newsletter") to send reports.
  - Include property-specific Coda document links dynamically in each report.

# Measurement Metrics 
- Efficiency Gains: Reduction in manual effort (e.g., hours saved monthly by automating the process).
- Timeliness: Percentage of reports sent on time 

# SLA 
- Efficiency Gains: Reduction in manual effort supposed to reduce up to 50% 
- Timeliness: Percentage of reports sent on time (target: 100% by the 3rd of each month).

# Mid Evaluation 
We failed to meet the SLA as the current process takes longer than sending emails manually, leading to user complaints.

## Actions Taken
- Feedback Addressed: User complaints have been reviewed, and a backlog of fixes created.
- Apology Issued: A formal apology has been sent to acknowledge delays and commit to resolutions.

## Complaints
- Reports are incorrectly sent to both owners and managers; they should go to owners only.
- Newsletter titles lack property names, making them hard to identify.
- Templates are not used as provided, causing inconsistencies.

## Next Steps
We will resolve these issues to improve efficiency and user satisfaction.

# Final Evaluation 
We are pleased to report that all these issues have been addressed:
- Improved Report Distribution: Reports are now sent to all relevant stakeholders, not just property owners.
- Newsletter Titles Enhanced: Titles on BIGRR now consistently include the property name, ensuring better clarity and identification.
- Template Utilization: We implemented verbatim mode, enabling the use of user-provided templates as requested.

To validate these improvements, we have provided 10 sample outputs for users to review, demonstrating that all requirements have been met to satisfaction.

**Comment by krisnaBukitVista** [comment]
Here's ten full board report newsletter examples:
https://bigrr.bukitvista.com/newsletter/818
https://bigrr.bukitvista.com/newsletter/817
https://bigrr.bukitvista.com/newsletter/816
https://bigrr.bukitvista.com/newsletter/815
https://bigrr.bukitvista.com/newsletter/814
https://bigrr.bukitvista.com/newsletter/813
https://bigrr.bukitvista.com/newsletter/812
https://bigrr.bukitvista.com/newsletter/811
https://bigrr.bukitvista.com/newsletter/810
https://bigrr.bukitvista.com/newsletter/809

**Comment by Vidiskiu** [comment]
Overall Point: 4.75
Functional Complexity: 1

> The functionality involves automating existing manual processes and integrating with an existing content creation system, which constitutes moderate complexity with relatively straightforward automation logic.

Technical Complexity: 1.75

> The issue requires significant technical work to integrate templates into the AION system and to automate the distribution process, including dynamic content insertion which increases the technical difficulty.

UI/UX Complexity and Impact: 0

> There is no specific UI/UX work mentioned in the issue description; therefore, it is not applicable in this context.

Testing and Quality Assurance: 1

> Testing is needed to ensure that automated reports are being generated and distributed correctly, and that the dynamic content insertion for property-specific links functions as expected. There is also a need to verify that the error handling from previous complaints has been resolved.

Risk and Dependencies: 1

> There is high risk considering there were previous user complaints, and dependencies are involved such as correct integration with AION and ensuring Coda document links work properly with each generated report.
