### ISSUE TITLE
Hospitality / Taking over SUP, SP, and SDP from partnership team

### ISSUE THREAD

**Issue by bstiawan** [Bukit-Vista/roadmap#11]
# Description

- We need to transfer the responsibility of labeling each property based on performance, from Kayla to Engineering (automation)
- Currently the classification goes as follows:
	- Spin up partnership (SUP) 
	- Standard Partnership (SP)
	- Spin down partnership (SDP)

# Problem

- Due to manual calculation and list creation there are 2 obvious problems:
	- Time taken takes up UM bandwidth
	- Decision could be subjective
- Updates on the labels will only occur when it is run, while in fact it could be live.

# Solutions

- Provide algoritm implementation to classify properties to SDP, SP, SUP in datavista.
- Create sceduler to evaluate the scores of all active property on the 1st, 7th, 14th, 21st, and 28th of every month.
   - The scheduler will calculate hospitality score, review conversion rate, and revenue generation. (period of -30 days)
   - It will then be mapped to the respective scores, and also its respective percentage contribution.
   - If the current date is 1, it will set active status to top 10 of SUP and SP, and active status to lowest 10 of SDP.
      - else, it will set the same active status following the last week.
- Creation of Property prioritization page
   - Has table that contain list of property, hospitality score, review conversion score, revenue score, and prioritization category. 
   - Filter includes: date (weekly), active inactive status (default active), prioritization.
   - Upon clicking the property, we are redirected to Property Detail > property prioritization history subpage.
- Creation of property priotitization history subpage
   - Has list of weeks and summary of stats (?)
   - Upon clicking the week, we are able to see the list of actionables
   - Actionables generated can be marked as complete, added, changed, or removed.
   - We can override the prioritization status and the active status.
- Creation of property prioritization control panel
   - Able to customize mapping of components from real value to score
   - Able to customize percentage contribution to overall percentage
   - Able to customize threshold for classification of SP, SDP, SUP

# Measurement metrics
- [3S Sheet manual calculation](https://docs.google.com/spreadsheets/d/17uFQ6MVUXHiwfDEy2MzqxmkN5Qvpp0K6_jlEG82RjKQ/edit#gid=0)
- Hospitality score for each level
- Revenue contribution for each level

## Current measurements:
- Time taken to generate list: 541 minutes

## SLA
- Time taken to generate list: <60 minutes (decrease 88.71%)

Team member:
- @Ardy-BukitVista
- @fanesz 

Updates: 
- Follow up to Kayla on 2024-04-21 to settle on the fixed manual workflow and KPI+SLA since right now there are still a lot of subjectivity and inconsistency in the manual execution.
- We have provided several suggestions as well pertaining to the improvement in manual execution evaluation such as conditions    https://bukitvista.slack.com/archives/C06RZ1WMK2R/p1711777857302469. 
- 2024-04-25: Kayla has finalized the metrics and methodology used in manual execution, still needs ideation and custom methodology from Engineering [sheet](https://docs.google.com/spreadsheets/d/17uFQ6MVUXHiwfDEy2MzqxmkN5Qvpp0K6_jlEG82RjKQ/edit#gid=0)

**Comment by bstiawan** [comment]
Development should be finished early May so we have time to evaluate the performance until end of month.

**Comment by Vidiskiu** [comment]
Updated client on the MVP methodology of prioritization: https://datavista.bukitvista.com/queries/1024

**Comment by Vidiskiu** [comment]
Overall Point: 5.3

Functional Complexity: 1.2

> Transferring labeling responsibility requires an understanding of business rules and implementing them into automation.

Technical Complexity: 1.4

> Requires development of algorithms for classification, building a scheduler, and a control panel, which are technically demanding tasks.

UI/UX Complexity: 0.5

> UI changes involve creating multiple new pages and controls, though utilizing standard interfaces.

Data Manipulation: 1

> Involves significant manipulation of property data, scores calculations, and maintaining history.

Testing: 0.4

> Testing automation logic and scheduling are needed, but fall within regular testing routines.

Dependencies: 0.4

> Relies on the existing data platform and external data input methods which are already in place.

Risk and Uncertainty: 0.4

> There's a moderate risk of algorithmic misclassification and the need to maintain accurate property statuses.

User Impact: 

> Directly impacts the effectiveness and efficiency of the property management process and user operations.

**Comment by krisnaBukitVista** [comment]
# Summary of the system:  

1. Automatic Property Classification:
- The system now automatically ranks properties without manual intervention.
- Users can still manually adjust the rankings if needed, providing flexibility and control.

2. Advanced Filtering Options:
- Filter rankings by the date they were generated.
- Display specific classifications only, making it easier to focus on particular categories.

3. Ranking History Tracking:
- Each property now has a detailed ranking history.
- Users can track whether a property is progressing or regressing over time.

4. Automatic Task Assignment:
- Tasks are now automatically assigned based on specific property components.
- For instance, if a property has a low review conversion rate, a task will be created for the operations team to encourage past guests to leave reviews.

# Development Plan
Next Enhancement (Scheduled for Next Week):
Automatically translate tasks into daily tasks in HubSpot. This integration will streamline task management and ensure all team members are aware of their daily responsibilities.

# Current Performance Review
- Efficiency: The ranking generation process now takes just 30 minutes, including potential delays. Previously, the manual process required 541 minutes.
- Accuracy: The ranking results are accurate, adhering to the evaluation and scoring methods agreed upon by the users, specifically Kak Kayla.
- Monitoring: We will continue to monitor the results and progress over the upcoming week to ensure continued accuracy and performance improvements.
