### ISSUE TITLE
AWS Database Migration Service to Jakarta Server

### ISSUE THREAD

**Issue by krisnaBukitVista** [Bukit-Vista/roadmap#113]
# Description 
The project involves migrating the current database service from the Ohio region to the Jakarta region using AWS Database Migration Service (DMS). This initiative aims to achieve better performance metrics, such as improved latency and success rates, by placing the EC2 and RDS in the same region. The migration will be conducted for both development and production environments.

# Problem
- Stress and spike testing have demonstrated that the latency and success rate are significantly better when both EC2 and RDS are located in the Jakarta region.
- Keeping the RDS in Ohio causes higher latency and suboptimal performance.
- Current architecture is not optimized for region-specific speed, leading to slower response times.

# Solution
- Migrate the database service from Ohio to Jakarta using AWS Database Migration Service.
- Conduct a phased implementation:
  - Research and configure AWS DMS to ensure compatibility.
  - Test the migration process in the development environment.
  - Roll out the migration to the production environment with minimal downtime.
- Validate post-migration performance improvements using key metrics.

# Measurement metrics
- Average Latency: Measure the time taken for database queries before and after migration.
- Success Rate: Evaluate the percentage of successfully executed database operations post-migration.

# SLA
- Average Latency: Below 250ms
- Success Rate: Above 90%

**Comment by RobinNusantara** [comment]
Percentile | Metric (Pre-Migration) | Metric (Post-Migration) | Improvement (%) | Observations
-- | -- | -- | -- | --
p50 | 26ms | 7.33ms | 71.8% faster | Significant reduction in median query time.
p75 | 234ms | 59ms | 74.8% faster | Noticeable improvement in query response at the 75th percentile.
p90 | 994ms | 299ms | 69.9% faster | Performance remains consistent as we move to higher percentiles.
p95 | 1,927ms | 678ms | 64.8% faster | Similar trend as the p90, showing consistent optimization.
p99 | 6,249ms | 2,634ms | 57.9% faster | Considerable performance improvement in edge cases.
p99.9 | 28,104ms | 12,679ms | 54.9% faster | Improved performance even for the most extreme cases.
Max | 47,696ms | 18,458ms | 61.3% faster | Maximum query response time has been drastically reduced.

<hr><h3><strong>Observations</strong></h3><ol><li><strong>Median (p50) Improvement</strong>: Post-migration, the median query time improved by ~72%, reflecting better average query performance.</li><li><strong>Higher Percentiles</strong>: Performance gains decrease slightly at higher percentiles (p99, p99.9), but all improvements remain above 50%.</li><li><strong>Maximum Query Time</strong>: The maximum query response time dropped from 47.7 seconds to 18.5 seconds, showing significant stabilization in worst-case scenarios.</li></ol><hr><h3><strong>Conclusions</strong></h3><ul><li>The migration resulted in substantial performance gains across all percentiles.</li><li>Median queries (p50-p75) saw the most dramatic improvements, making user experience significantly better.</li><li>High-latency outliers (p99 and above) were also improved, though there’s still room for further optimization in extreme cases.</li></ul>

**Comment by RobinNusantara** [comment]
Query | Metric | Before Migration | After Migration | Change | Observation
-- | -- | -- | -- | -- | --
select_user.user_id_user.name_user...is_email_1c755 | Median (p50) | 10.16s | — | — | No median data for after migration.
  | Max | 20.33min | 14.1s | ~99% faster | Maximum time improved drastically.
select_newsletters._from_select_newsletters..._id_newsletter_title_16875 | Median (p50) | 9.93s | — | — | Missing p50 values for comparison.
  | Max | 27.80min | 11.1s | ~99% faster | Significant improvement in maximum response time.
select_user.user_id_user.name_user...employee_job_title_name_2190e | Median (p50) | 9.89s | — | — | Median data is absent for post-migration.
  | Max | 19.45min | 11.1s | ~99% faster | Maximum query execution time reduced significantly.
select_count_from_select_newsletters...id_name_newsletter_titles.title_bc22e | Median (p50) | 9.80s | — | — | No post-migration median data available.
  | Max | 27.44min | 18.4s | ~99% faster | Considerable drop in the longest query time.
select_count_from_select_newsletters...id_name_newsletter_titles.title_dd634 | Median (p50) | 9.39s | 5.71s | 39% faster | Median query execution time improved.
  | Max | 7.36min | 5.9min | 20% faster | Smaller improvement in extreme cases.
select_newsletters._from_select_newsletters...id_newsletter_title_e5f1b | Median (p50) | 9.31s | 5.55s | 40% faster | Median query execution reduced.
  | Max | 7.29min | 5.73min | 22% faster | Marginal improvement in maximum response time.
select_property.bv_nett_-_property.payout_bv...owner_nett_from_sele_50ddf | Median (p50) | 7.37s | — | — | Post-migration median data missing.
  | Max | 17.43min | 6.0s | ~99% faster | Significant improvement in max execution time.
select_count_distinct_user...employee_role_on_employee._employee_id_employe_6e9d4 | Median (p50) | 7.08s | 5.97s | 15% faster | Small but notable improvement in median time.
  | Max | 2.24min | 6.0s | 96% faster | Drastic reduction in maximum response time.

<hr><h3><strong>Overall Trends</strong></h3><ol><li><strong>Dramatic Improvements in Max Times</strong>: Across most queries, the maximum execution time was significantly reduced post-migration, often by over 90%.</li><li><strong>Median Times Improved Modestly</strong>: While some queries saw substantial gains in median performance (e.g., <code>select_count_from_select_newsletters...</code>), others showed limited or no improvement.</li><li><strong>Incomplete Metrics</strong>: Some queries lack sufficient data for comparison, particularly around post-migration p50 metrics.</li></ol><hr><h3><strong>Conclusion</strong></h3><ul><li>Migration yielded <strong>substantial gains in performance</strong>, particularly for outlier cases (maximum response times).</li><li>Median performance has improved in many cases but not universally.</li><li>Missing post-migration median metrics (p50) limit a complete comparison. Filling these gaps can help further evaluate performance impacts.</li></ul><p></p>

**Comment by RobinNusantara** [comment]
The data only shows the top 10 queries before and after migration. Looking at the data on Datadog, the latency of the queries has significantly decreased. However, the performance for the newsletter feature is very poor. This is because, in the top 10 queries, the queries from the newsletter feature often rank at the top for average latency, which is quite high. Therefore, query optimization and reindexing are necessary.

**Comment by Vidiskiu** [comment]
Overall Point: 5
Functional Complexity: 1.5

> The functional complexity is high due to multi-environment migration and performance validation, but not the highest due to existing solutions like AWS DMS.

Technical Complexity: 1.5

> Moderate technical difficulty due to the use of a managed service (AWS DMS) but the need to conduct testing and handle a production migration increases technical complexity.

UI/UX Complexity and Impact: 0

> No UI/UX complexity is involved in a database migration process.

Testing and Quality Assurance: 1

> Migration requires significant testing in dev and prod, with strong focus on performance metrics; however, AWS DMS reduces some testing complexity.

Risk and Dependencies: 1

> High risk due to production environment impact and stringent SLA requirements, along with the complexity of region migration.
