### ISSUE TITLE
Iteration #2/ 100% unsupervised automated revenue projection process

### ISSUE THREAD

**Issue by Vidiskiu** [Bukit-Vista/roadmap#15]
# Description
- Revenue projection automation still need human involvement, this adds time to process and the resource is limited.
- The projection should be fully automated
- Human only need to supervise the result, not the process
- The previous milestone https://github.com/orgs/Bukit-Vista/projects/3/views/1?pane=issue&itemId=60793479 was not achieved.

# Problem
- Processes that are still manual:

1. ~Expense data of the property is still static~ **Done**
2. ~Attachment of figure for total review for nearby properties.~ **Done**
3. ~Attachment of figures for booking window from Redash~ **Done**
4. ~Attachment of figures for length of stay from Redash~ **Done**
5. ~Nearby restaurant figures close to the property~ **Done**
6. ~Airport map figure to the property is still limited to Ngurah Rai Airport~ **Done**
7. ~ADR calculation using xgboost is still incorrect~ **Done**
8. ~Successful design reference for the property~ **Done**

# Solutions
- Based on the available feature submitted in the form, we will keep a fixed cost to be multiplied by the measurements to get the cost
> e.g. Pool size 21m^2, multipied by $3 dollars/meter/month for maintenance.
- Create at least 2 location for Airport, finding the closest airport, NYIA and Ngurah Rai Airport using gmaps embedding [issue](https://github.com/orgs/Bukit-Vista/projects/1/views/2?sliceBy%5Bvalue%5D=Revenue+Projection%401.9&pane=issue&itemId=62072775)
- Create plot at least 3 high performing restaurants and map figure to coda based on map_objects table using gmaps embedding [issue](https://github.com/orgs/Bukit-Vista/projects/1/views/2?sliceBy%5Bvalue%5D=Revenue+Projection%401.9&pane=issue&itemId=62072263)
- Plot data from airbnb_map_objects to create fig of total review count by room count [issue](https://github.com/orgs/Bukit-Vista/projects/1/views/2?sliceBy%5Bvalue%5D=Revenue+Projection%401.9&pane=issue&itemId=62069155)
- Fetch data from redash through apollo and create figure within Apollo [issue_1](https://github.com/orgs/Bukit-Vista/projects/1/views/2?sliceBy%5Bvalue%5D=Revenue+Projection%401.9&pane=issue&itemId=62070588) [issue_2](https://github.com/orgs/Bukit-Vista/projects/1/views/2?sliceBy%5Bvalue%5D=Revenue+Projection%401.9&pane=issue&itemId=62071049)
- Improve ADR generation for the predicted property [issue](https://github.com/orgs/Bukit-Vista/projects/1/views/2?sliceBy%5Bvalue%5D=Revenue+Projection+%40+2.0&filterQuery=-status%3A%22%E2%9C%85+Released%22%2CInvalid+-milestone%3A%22*%40future%22%2C%22Listing+Content+Management+%401.1%22%2C%22Newsletter+V3%22&pane=issue&itemId=62073309)
- Store knowledge of design reference from data base to CODA.
- Make revenue projection form accessible within less than 3 clicks to potential partner

# Measurement metrics

- [GAIA Revenue Projection Slack Channel](https://bukitvista.slack.com/archives/C065C0R4E13)

## Current measurements:
- About 30 revenue projections that was inserted by execution team, 0% are processed automatically.

## SLA
- [ ] Minimum 10 projections be 100% automated, this includes the input from internal team: Not achieved: 20% success rate

**Comment by Ardy-BukitVista** [comment]
Example for Full board Package : [Full Board Package Document](https://coda.io/d/Inspired-Investment-Business-Plan-for-Balangan-by-Bukit-Vista_d5QmwFpcvXb/Inspired-Investment-Business-Plan-for-Balangan-by-Bukit-Vista_sufMk#_luNDk)
Example for Business Plan : [Business Package Document](https://coda.io/d/Inspired-Branding-Rencana-Bisnis-untuk-Villa-Ailee-by-Bukit-Vist_dYYl11ISy0C/Inspired-Branding-Rencana-Bisnis-untuk-Villa-Ailee-by-Bukit-Vist_sufA0#_luRwI)

**Comment by Vidiskiu** [comment]
Updates:

- Evaluation was submitted by RM team on sample revenue projections on 2024-06-15
- Out of the 10 samples, only 2 were accepted as minimal supervision required.

**Comment by Vidiskiu** [comment]
Overall Point: 5.8

Functional Complexity: 1.3

> Achieving a 100% automated revenue projection process involves significant refinement of existing systems, requiring complex business rule implementation and possibly new feature development.

Technical Complexity: 1.3

> The automation of data fetching, calculation, and integration with various services such as Google Maps and Redash, indicates high technical complexity.

UI/UX Complexity: 0.7

> The need for an accessible form with less than 3 clicks for potential partners implies thoughtful UI/UX design but within a moderate complexity range.

Data Manipulation: 0.9

> Data manipulation is critical here, as the projection will depend on dynamically calculated metrics and external data sources, though some groundwork has already been laid.

Testing: 0.3

> While the success rate will likely require rigorous testing and validation, particularly for the automated calculations, it is somewhat mitigated by existing success metrics.

Dependencies: 0.4

> The dependency on external APIs and possibly new tools for embedding adds a layer of complexity but is not wholly reliant on uncertain or unstable dependencies.

Risk and Uncertainty: 0.3

> Automating critical business processes like revenue projections brings inherent risks, but precise measurement metrics and SLAs can help manage uncertainty.

User Impact: 0.6

> Fully automated projections have a high user impact by improving the efficiency and user experience for the execution team, but direct end-user impact is more contained.
