### ISSUE TITLE
Excellent Guest Experience Prioritization

### ISSUE THREAD

**Issue by bstiawan** [Bukit-Vista/roadmap#17]
# DESCRIPTION 
The "Enhancement for Operational Flow" project aims to streamline and improve the efficiency of the operational processes within the organization. This initiative focuses on three main tasks designed to enhance communication prioritization, integrate critical handover processes into a centralized system, and provide a comprehensive dashboard for case management.

# PROBLEM 
- Currently, high-priority messages are scattered across various channels, leading to delays in response times and inefficiencies in handling urgent matters. This lack of prioritization can result in operational disruptions and negatively impact service quality.
- Supervisors currently struggle to manage multiple separate Coda docs, making it difficult to maintain oversight and ensure smooth handovers. This fragmentation leads to inefficiencies and potential errors in the handover process.
- Case managers currently lack a centralized tool to monitor and prioritize their workload effectively. This can lead to missed or delayed responses to critical issues, negatively impacting guest satisfaction and operational efficiency.

# SOLUTIONS
- By creating the GAIA-hosting-priority channel, all high-risk and time-sensitive messages will be centralized, allowing for better prioritization and quicker response times. This will enhance the operational flow and ensure that critical issues are addressed without delay.
- Moving all handover processes to HubSpot will centralize the information, making it easier for supervisors to monitor and manage. The introduction of shortcut buttons in GAIA thread messages will further streamline the process, allowing for quick and easy forwarding of messages to the relevant handover sections, thereby enhancing efficiency and reducing the risk of errors.
- The case manager dashboard will provide a real-time overview of key metrics, enabling case managers to quickly identify and address high-priority issues. By focusing on missed chats, sentiment analysis, and unresolved complaints, the dashboard will help case managers strategically allocate their attention and resources to where they are needed most, improving overall operational effectiveness and guest satisfaction.

# GAIA HOSTING PRIORITIZATION 
after doing analysis on negative reviews for May, we came  up with category that tend to result on bad review so we need to prioritize this category below 

(Problem, Resolution)

- request_guest_size_alteration (Easy, Easy)
- request_late_check_in, (Easy, Easy)
- request_extra_service, (Hard, Easy)
- request_late_check_out (Hard, Easy)
- request_extension (Easy, Easy)
- request_cancellation (Hard, Hard)
- request_shorten_alteration (Hard, Hard)
- request_early_check_in (Hard, Easy)
- request_luggage_drop, (Easy, Easy)
- feedback_negative: (Hard, Hard)
- request_onsite: (Easy, Easy)
- request_scooter_or_bike (Easy, Easy)
- request_special_occasion (Hard, Hard)
- request_special_requirements (Hard, Hard)

# CASE MANAGEMENT DASHBOARD 
the dashboard will include 4 components
- Missed chat: checking whether or not the guest has last message with no reply in one day
- Unresolved complaints: summarize the conversation and let AI decide whether or not we have unresolved complaints
- Urgency level:
low = Don't have to be done today
medium = Need between 2 hours and one day
high = Anything that needs immediate action
- Average of sentiment analysis 

# SCORING SYSTEM 
- Missed chat (yes: 0 & no: 10)
- Unresolved complaints (yes: 0 & no: 10)
- Urgency level (low: 10 & medium: 5 & high: 0)
- Average of sentiment analysis

# RANKING SYSTEM 
(20% * score from missed chat) + (20% * score from unresolved complaints) + (30% * sentiment analysis) + (30% * urgency level)

# MEASUREMENT METRICS

![Image](https://github.com/Bukit-Vista/roadmap/assets/149347254/cbfda717-8c77-4128-ada7-71ee61eeb427)

On may evaluation, we got 
- 3.96 : 1 for the 5-stars win loss
- 0,46 review conversion rate
- 887 review received 

# SLA
5-star review win-loss

# EVALUATION 
- 4.19 : 1 for the 5-stars conversion rate 
- 0,43 review conversion rate 
- 794 review received

**Comment by bstiawan** [comment]
@krisnaBukitVista unclear goal and approach. How do you define high priority guests?

**Comment by krisnaBukitVista** [comment]
@bstiawan 
- I have attached the measurement metrics and the SLA based on previous review analysis on May 
- I have added the category that should be on high priority and how do we get them 
- I have submitted the component of dashboard and how do we get to the scoring system

**Comment by krisnaBukitVista** [comment]
we have done for the development, we just need to wait until June for the evaluation

**Comment by Vidiskiu** [comment]
Overall Point: 6.7

Functional Complexity: 1.2

> The enhancement involves multiple operational processes that are crucial for improving communication and service quality within the organization.

Technical Complexity: 1.4

> Integrating various communication channels and handover procedures into central systems such as HubSpot, including the implementation of GAIA-hosting-priority and dashboard components, presents significant technical challenges.

UI/UX Complexity: 0.9

> Creating a user-friendly centralized dashboard for real-time monitoring of key metrics requires careful consideration of UI/UX design to ensure clarity and efficiency for end-users.

Data Manipulation: 0.9

> Manipulation of large volumes of operational data, including prioritization, sentiment analysis, and handover processes, is complex and requires robust data handling strategies.

Testing: 0.5

> Extensive testing is required to ensure the reliability of the communication prioritization, handover processes, and dashboard functionality, within the constraints of the maximum allowable score.

Dependencies: 0.4

> The solution has several dependencies including third-party services like HubSpot and potential integration with existing internal tools, though it is anticipated to be in control.

Risk and Uncertainty: 0.4

> There is some risk involved in accurate data representation and ensuring the operational flow is not disrupted during the transition to the new system, but the risks are not considered exceedingly high.

User Impact: 1

> Improvements in operational efficiency and response times directly impact guest satisfaction and service quality, leading to a high user impact.
