### ISSUE TITLE
Hospitality / Increase Communication 5 star rating

### ISSUE THREAD

**Issue by bstiawan** [Bukit-Vista/roadmap#2]
# Description 
We want to ensure GAIA has positive contribution on increasing the effectivity and efficiency in communication aspect

# Problem
We still have various issue related to category and tools enhancement 

# Solution
Completing the milestone GAIA 1.2.7
- Enhance categories & tools (knowledge, prompts, description)
- Enhance User Experience
- Solving Edge Case Bug (related to images)
- Personalize gaia agent
- Automatically opt-out message in certain category

# Measurement objective
- increasing the communication aspect on hospitality score 

# SLA
- increasing the communication aspect on hospitality score to 85% in May

# Result of evaluation
- We only got 84.6% for communication on May 

![Image](https://github.com/Bukit-Vista/roadmap/assets/149347254/cb708942-32a0-4cc4-88cb-ddc7b8904c7f)

- If we take a look on bigger perspective, GAIA only contribution after completing milestone 1.2.7 is maintaining the review on communication 

![Image](https://github.com/Bukit-Vista/roadmap/assets/149347254/ec61dad9-ae69-4e17-99d3-688982d68983)

# Analysis of the issue 
- There is one critical mistake by GAIA resulting on bad review which are GAIA always provide exception when guest is begging for it
- This is mostly applied with cancellation and alteration request

# Next action
We continue on improving the weakness and we have several enhancement for GAIA in next milestone 1.2.8

**Comment by bstiawan** [comment]
@vitomichael this is unclear target.

- No goal
- The title is an activity, not achievement
- No clear measurement, I've added 85.5% as target
- No information about current performance (category error rate) and what's the target that want to be achieved

**Comment by vitomichael** [comment]
1. The goal is increase the communication 5-star rating. The target is 85.5%
2. I've list the activity to achieve this goal.
3. We already have tool error rate in Datavista
4. Enhance categorization

**Comment by Vidiskiu** [comment]
Overall Point: 4.4

Functional Complexity: 0.9

> Enhancing communication categories and tools requires a good understanding of user needs and effectively categorizing them, which brings moderate functional complexity.

Technical Complexity: 0.6

> While there is some technical effort involved in improving tooling, the tasks seem to be iterative enhancements rather than deep technical challenges.

UI/UX Complexity: 0.8

> Improving the user experience is a nuanced task that requires attention to detail, particularly since it involves the personalization of an agent and image handling which can be quite intricate.

Data Manipulation: 0.5

> The issue involves some data manipulation, especially when personalizing the gaia agent and managing the opt-out messages, but this is not extremely complex.

Testing: 0.4

> Ensuring the enhancements work as expected across various scenarios will require careful testing, particularly for the edge case bug and user personalization.

Dependencies: 0.3

> The enhancements may depend on previous versions and external libraries, but there isn't much indication of a large web of dependencies.

Risk and Uncertainty: 0.4

> There are some risks in user experience and edge case bugs, but the uncertainty seems controlled and mostly related to iterative improvements.

User Impact: 0.5

> Improving communication can have a significant impact on user satisfaction, but the impact is measured incrementally and the specific goals are precise, reducing the scope of impact.
