### ISSUE TITLE
Iteration #2 / Increase communication rating to 85%

### ISSUE THREAD

**Issue by krisnaBukitVista** [Bukit-Vista/roadmap#23]
# Description
This project aims to decrease manual workload by enhancing categories that still require human intervention within GAIA. Our focus is on improving the efficiency of these categories to streamline operations and enhance service delivery. 

# Problem
- Partial Escalation Requiring Human Intervention: Many categories remain stuck in a state of partial escalation due to the necessity of human intervention. Tasks such as requests for early check-in require manual handling for calendar blocking and payment coordination
- Redundant Categories Leading to Sub-Optimal Answers: The presence of many redundant categories results in sub-optimal answers. This redundancy complicates the categorization process, leading to inconsistent and less effective responses
- Reliability Issues with Essential Tools: There are reliability concerns with crucial tools, such as forwarding information to staff.

# Solution
- Effective Policy Implementation to Reduce Manual Work: We have implemented an effective policy aimed at reducing manual work. You can check it [here](https://github.com/Bukit-Vista/olympus-microservices/issues/870)
- Enhanced Reliability for Essential Tools: We have prioritized increasing the reliability of essential tools frequently used within BVGO operations. You can check it [here](https://github.com/Bukit-Vista/olympus-microservices/issues/871)
- Improved Category Efficiency through Tool Alignment: We are enhancing category efficiency by aligning tools with specific categories that typically require manual intervention based on analyzed data. You can check it [here](https://github.com/Bukit-Vista/olympus-microservices/issues/889)
- Automation of 'Request Onsite' Category: We are automating the 'Request Onsite' category by implementing a system to match guest requests with onsite capabilities. You can check it [here](https://github.com/Bukit-Vista/olympus-microservices/issues/865)

# Measurement objective
- Clear definition of categories that will be automated and non-automated. 
- We will only have 2 escalation status observed here: being No Escalation and Full Escalation.
- Categories that is determined to be no escalation should have 100% no escalation rate.

# SLA
- Clear definition of categories that will be automated and non-automated. 
- We will only have 2 escalation status observed here: being No Escalation and Full Escalation.
- Categories that is determined to be no escalation should have 95% no escalation rate.
- 85% Communication Rating on July 2024 (?)

# Team Member
@rifqinvnd @vitomichael

**Comment by bstiawan** [comment]
@vitomichael @Vidiskiu unclear goal and actions here.

**Comment by Vidiskiu** [comment]
Overall Point: 5.8

Functional Complexity: 1.1

> Reducing manual workload by enhancing certain process areas involves changes to workflows and could have a broad impact on the operational structure.

Technical Complexity: 1.3

> Improving the efficiency of categories and automation entails complex integrations and logic handling to ensure proper category alignment and automation.

UI/UX Complexity: 0.6

> UI/UX changes may be involved to align tools with categories and to support automation, but the complexity is not overly high given the description.

Data Manipulation: 0.9

> Data analysis and effective categorization to reduce human intervention will require significant data manipulation efforts.

Testing: 0.4

> Testing the implemented solutions and policies will be crucial to ensure the reliability and effectiveness of the enhancements.

Dependencies: 0.4

> The project likely involves coordination between different systems and improvements, which introduces dependencies, although not to a maximal degree.

Risk and Uncertainty: 0.4

> There are inherent risks in the scope and accuracy of automating categories, and reducing reliance on manual processes may introduce uncertainties that need to be managed.

User Impact: 0.7

> Enhancing operational efficiency can greatly improve the end-user experience through faster and more reliable service, but its direct impact is somewhat mitigated by its internal focus.
