### ISSUE TITLE
Iteration #2 / Taking over SUP, SP, and SDP from partnership team

### ISSUE THREAD

**Issue by krisnaBukitVista** [Bukit-Vista/roadmap#24]
# Description 
It is an enhancement from the previous project on 3S automation which you can see here: https://github.com/Bukit-Vista/roadmap/issues/11

# Problem 
- User need to download the file so that they can see it offline 
- Need to increase the user comfortability by directly write the main task on the title instead of description and better label for status colomn in the main table
- Still requires manual assignment from BIGRR to hubspot 
- Lack of flexibility in customizing the period of time for scoring

# Solution
- button to download CSV file for full ranking
- move content of task description to title of task description
- connect task list to hubspot task assignment
- change activity status colomn
- create customization range of date for user
- add filter for property name

Version issues: https://github.com/orgs/Bukit-Vista/projects/1/views/2?sliceBy%5Bvalue%5D=3S+Property+Prioritization+%401.1+-+Integrations+with+Hubspot

# Measurement metrics
- [x] All tasks should be accurately forwarded to hubspot

# SLA
- [x] 100% task generated from property classification should be forwarded to hubspot

# TEAM MEMBER
@RobinNusantara

**Comment by Vidiskiu** [comment]
- Disable Export button during loading filtered table

**Comment by Vidiskiu** [comment]
Overall Point: 5.6

Functional Complexity: 1.2

> The enhancement covers multiple integrated functionalities like ranking, CSV download, and HubSpot integration, increasing functional complexity.

Technical Complexity: 1.3

> Technical challenges involve integration with third-party services like HubSpot and ensuring data consistency during the process.

UI/UX Complexity: 0.6

> The UI/UX complexity involves rearranging user interface elements and improving label clarity, which requires thoughtful design but is not the highest level of complexity.

Data Manipulation: 0.7

> Data manipulation for CSV generation and synchronization with HubSpot is non-trivial but is a well-understood problem.

Testing: 0.5

> While automatic forwarding to HubSpot must be thoroughly tested, the overall testing falls within regular boundaries and does not demand excessive complexity.

Dependencies: 0.3

> The task depends on external APIs and services but is designed with these dependencies in mind, minimizing this complexity.

Risk and Uncertainty: 

> 

User Impact: 1

> Enhancements aimed at increasing user comfort and task management efficiency have a direct and positive impact on users.
