### ISSUE TITLE
Revenue / Increase Conversion Rate 20% daily consistently

### ISSUE THREAD

**Issue by krisnaBukitVista** [Bukit-Vista/roadmap#25]
# Description
The objective of this project is to enhance the existing AI system, MOR, to automatically offer cross-selling opportunities. The enhancements will include updating event information, integrating hyperlinks for quicker manual follow-up, adding more models to offer on short periods of checking out, and incorporating guest sentiment analysis for validation.

# Problem
- Outdated Event Information
- Inefficient Manual Follow-Up
- Limited Cross-Selling Models
- Lack of Sentiment-Based Validation

# Solutions
task written on GAIA MOR @1.1 [here](https://github.com/orgs/Bukit-Vista/projects/1/views/2?sliceBy%5Bvalue%5D=GAIA+MOR+%401.1&filterQuery=-status%3A%2CInvalid+-milestone%3A%22*%40future%22%2C%22Listing+Content+Management+%401.1%22%2C%22Newsletter+V3%22%2C%22Revenue+Projection+%40+2.0%22%2C%22Community+Manager+%401.0.1%22%2C%22Community+Manager+%401.0.0%22%2C%22GAIA+%401.2.9+Expanding+Ability%22%2C%22Athena+%401.0.3%22)
Update the Event Information
- Label "Failed Inquiry" or "Cross-Selling": Clearly label each follow-up event to distinguish between failed inquiries and cross-selling opportunities.
- Provide User Last Messages and GAIA Answer: Include the last message sent by the user and the corresponding response from GAIA in the follow-up data. This helps provide context and continuity in communication.
- Comparison Between Current Inquiry and Cross-Sell Offer: Present a clear comparison between the original inquiry and the cross-sell offer. This highlights the benefits or alternatives being suggested.
- Sentiment Analysis Data: Incorporate sentiment analysis of the user's previous messages to tailor the follow-up approach based on the guest's mood and likelihood to convert.

 Add Hyperlink to Airbnb for Quicker Manual Follow-Up
- Making it easier for reservation team to do follow up such as providing special offer 

Add More Models to Offer on Short Period of Checking Out
- Provide model that focuses on short period of check-out such as 2 days

Add Validation Based on Guest Sentiment Analysis
- Implement sentiment analysis tools to assess the tone and content of guest feedback and inquiries.
- Use sentiment data to validate follow-up messages, ensuring they are appropriately tailored to the guest's mood and likelihood to convert.

# Measurement metrics
Conversion Rate: Track the percentage of follow-up inquiries that result in bookings.

# SLA
The Service Level Agreement (SLA) for this project is to achieve a 20% conversion rate on follow-up inquiries within one month of implementing the enhancements.

# Prioritization result
## Relevancy 
- Revenue Potential: Implementing this strategy can significantly boost our revenue by providing guests with compelling reasons to extend their stay.
- Strategic Location: Showcasing local events highlights the strategic location of our properties. This not only serves as an attraction for potential guests but also enhances our location rating as a secondary benefit.

## Feasibility
- Event Information and Hyperlink Updates: We have successfully implemented event information and hyperlink updates on other GAIA channels. 
- Validation Modification: The methods required for validation modifications are already in place. We can leverage sentiment analysis with only minor adjustments, ensuring that the implementation process is efficient and effective.
- Model Experimentation: We possess the necessary model framework. By modifying specific variables, such as the checkout date, we can tailor the models to meet the new requirements.

## Impact 
- Conversion Rate: With this project, we aim to achieve a consistent 20% conversion rate, driven by the added value and convenience of providing updated event information to our guests.
- Location Rating: By highlighting the vibrant events around our properties, we aim to increase our location rating by 5%. This improvement will make our properties more appealing to potential guests, enhancing our overall market competitiveness.

# Team Member 
@rifqinvnd

**Comment by katibpasha** [comment]
Will be evaluated by @katibpasha

**Comment by katibpasha** [comment]
The development stage has been finished on Aug 16th 2024.

- The location rating

**Comment by Vidiskiu** [comment]
Overall Point: 6.1

Functional Complexity: 1.1

> Enhancing the AI system to support cross-selling involves several functional improvements which are innovative but fairly complex to integrate cohesively.

Technical Complexity: 1.1

> Technical complexity is high due to the integration of sentiment analysis and the need to update models for different scenarios, although existing frameworks and methodologies may ease the process.

UI/UX Complexity: 0.6

> While UI/UX changes seem minor, the incorporation of hyperlinks and clear labeling demands thoughtful design to improve efficiency for manual follow-ups.

Data Manipulation: 0.9

> Significant data manipulation is required to manage event information, sentiment analysis data, and model outputs to provide actionable insights.

Testing: 0.5

> Rigorous testing is necessary to ensure the reliability of new features and their impact on conversion rates, warranting maximum score within this category.

Dependencies: 0.4

> There are dependencies such as external sentiment analysis tools and data from Airbnb which add complexity, but these integrations are manageable given prior experience.

Risk and Uncertainty: 0.5

> Any update to the revenue-generating components includes the risk that changes may not yield the expected conversion rate increase, justifying the highest score within this limit.

User Impact: 1

> Successfully improving conversion rates and guest experiences with more personalized follow-ups has a direct and substantial impact on revenue and user satisfaction, deserving the highest allocation.
