### ISSUE TITLE
Revenue / 100% unsupervised automated revenue projection process

### ISSUE THREAD

**Issue by bstiawan** [Bukit-Vista/roadmap#3]
Problem:
- Revenue projection automation still need human involvement, this adds time to process and the resource is limited

Goal:
- The projection should be fully automated
- Human only need to supervise the result, not the process

Measurement:
- Minimum 5 projections after 26 April will be 100% automated

**Comment by bstiawan** [comment]
@Ardy-BukitVista @bellabukitvista please report your progress here.

**Comment by Ardy-BukitVista** [comment]
Update : 

- [ ] Location google maps estimated from location to airport
- [ ] Auto placement 2 tops restaurant (Highest Review Rating and Highest Review Count)
- [ ] New template for Business Package and Full Board Package

For 25-04-2024

- [ ] Fix Send Email (New Issue : there still error when button send to client pushed, there still bug cause new email template)
- [ ] Insert Expenses and Design Reference

**Comment by Vidiskiu** [comment]
@Ardy-BukitVista please update the updated response from Bella. From my understanding, Bella required the dynamic expense to be delivered first by 2024-05-05

**Comment by Ardy-BukitVista** [comment]
Update Dynamic Expenses
- [ ] Fixed - Salary
- [ ] Fixed - Pool
- [ ] Fixed - Maintenance
- [ ] Fixed - Electricity
- [ ] Fixed - Water
- [ ] Fixed - Internet
- [ ] Fixed -Trash Collection
- [ ] Fixed - Banjar Fee
- [ ] Least - Electricity
- [ ] Least - Water
- [ ] Least - Laundry
- [ ] Least - Guest Supplies
- [ ] Average - Electricity
- [ ] Average - Laundry
- [ ] Average - Water
- [ ] Average - Guest Supplies

**Comment by Vidiskiu** [comment]
- We conclude that this milestone was not achieved in delivering 5 automated revenue projection.
- Understanding the importance of acquisition of pAUM, we will refine the solutions given and iterate on this milestone https://github.com/orgs/Bukit-Vista/projects/3/views/1?pane=issue&itemId=61949335

**Comment by Vidiskiu** [comment]
Overall Point: 5.9

Functional Complexity: 0.9

> Fully automating revenue projection process requires strategic adjustments to existing systems and can have multiple functions that interact with various other platform components. Complexity is moderate due to need for automation across different parameters.

Technical Complexity: 1.2

> Technical issues include building or improving algorithms for projections, handling exceptions, and integrating with existing systems. It involves a high level of skill but is within the realm of well-understood data processing tasks.

UI/UX Complexity: 0.5

> While the main focus is on backend automation, there may be minor UI/UX considerations for presenting automated results and alerts, resulting in a moderate complexity score.

Data Manipulation: 1

> Data manipulation is fundamental to the task, as the projections are based on varied and potentially large data sets that must be handled accurately and efficiently.

Testing: 0.3

> Quality assurance is important to ensure reliability of automated projections. Given the nature of the task, a robust set of test cases will be necessary, but not unusually complex.

Dependencies: 0.4

> Dependencies may include data sources, scheduling tools, and possibly machine learning libraries which represent a moderate level of external reliance.

Risk and Uncertainty: 0.6

> There's some risk in automating financial projections due to the potentially high impact of errors, but the use of historical data for validation reduces uncertainty.

User Impact: 1

> If successful, the automated process will have a significant positive impact on the users who currently spend time on manual projections, by freeing up their resources and ensuring consistent output.
