### ISSUE TITLE
Attained 0.6 Reviews Conversion Rate

### ISSUE THREAD

**Issue by katibpasha** [Bukit-Vista/roadmap#31]
# Description
Aims to increase the Review Conversion Rate to push the [5-star rating goal](https://coda.io/d/Chapter-and-Team-Management_dAzjTEwEvGp/Semester-5-Milestones-On-Going_suLb1#Monthly-Strategic-Milestones_tugAY/r63&view=modal) and Overall Ratings

# Problem
We still have low score of Review Conversion Rate (0.45 rate updated on Jul 25 2024 2:00 pm). It may cause the 5-star rating doesn't achieved the goal. ([data](https://datavista.bukitvista.com/queries/590?p_date=d_last_90_days#2177))

![Image](https://github.com/user-attachments/assets/3dd30366-26df-4570-89d1-6cd0030fae2c)

![Image](https://github.com/user-attachments/assets/334b592e-e1bc-4ca9-8fef-97ac833e21af)

# Solution
Here is the current flow of guest status (confirmed by Sarah (GEM))

![Image](https://github.com/Bukit-Vista/roadmap/assets/74033435/eb027e3d-8c58-49c6-bb0e-c2771af5645a)

And here are some proposed action to push review conversion rate:

1. There is check-out reminder message but there is no narrative to encourage guests to give their reviews after they checked-out. We can **add the message content about the giving a review** there. (user research [result](https://docs.google.com/spreadsheets/d/1z7_kazER8kHV1JBsoap5XMnX652VR6QfuZgy_Ih_7Eg/edit?gid=0#gid=0))
2. We can automate the tools below and integrate these tools log to [this](https://datavista.bukitvista.com/dashboards/155-review-reminders?p_date=d_last_30_days) data source to monitor the effectiveness:
    - Pre-checkout review request message (only send this message to a guest with positive conversation sentiment)
    - Guest profile review
    - D+3, D+7, and D+12 review request message

![Image](https://github.com/user-attachments/assets/2422bda0-8720-453a-8ed7-85d4573526b3)

# Measurement Objective
- Review conversion rate is increasing higher that current rate (0.45)
- The increase of overall rating on review

# SLA
- [ ] We aim to achieve a review conversion rate of 0.6 by August 31, 2024.
I calculated the average number of bookings from April to July 2024, which is 1,704 bookings per month ([data](https://datavista.bukitvista.com/queries/590?p_date=2024-07-01--2024-07-31)). For August 2024, I predict the booking count will increase by this average, resulting in 6,819 (current booking count) + 1,704 (average monthly booking) = 8,523 total bookings. To achieve a 0.6 review conversion rate, we need at least 5,114 bookings to convert to reviews.
- [ ] Can achieve an "overall rating" 4.8 by August 31, 2024.

# Prioritization Result
- Relevancy: One of our goals for semester 5 is to achieve an overall rating of 4.8. Our current overall rating is 4.71. By increasing the review conversion rate, we can support the process of reaching this target.
- Feasibility: For review request message and tools automation are possible to be executed by engineering team.
- Impact: By offering an easy way for guests to leave reviews or providing incentives, we can increase the review conversion rate and support achieving the 4.8 overall rating target.

# Team Member
@RobinNusantara

**Comment by katibpasha** [comment]
Others recommendation:
1. For pragmatic guests, we can give them discount for next booking as a reward of giving a review (need confirmation to revenue management team), then engineering team could provide the logic flow in the app
2. Put a kind of attractive QR code in the room property for guests to give their reviews easily. Redirect to https://www.airbnb.com/trips

**Comment by katibpasha** [comment]
Will be evaluated by @katibpasha

**Comment by katibpasha** [comment]
# Evaluation Result
The development stage has been finished on Aug 16, 2024, with Robin as the programmer.

## Review Conversion Rate
Back then, we planned in last August we'll have at least 8.523 number of bookings. And now per Aug 28, 2024 we have 9.020 bookings 

![Image](https://github.com/user-attachments/assets/5579e8fd-d1e3-409f-ae6a-3e05efa001a8)

But we have result below the expectation for review conversion rate. We only have 4.057 reviews per Aug 28, 2024. It still far from the planned target, 5.114 reviews 

![Image](https://github.com/user-attachments/assets/f32f38bb-6be3-4a1e-b8ad-9a43eaf00601)

For the review conversion rate, we are failed to achieve the target. The rate still on 0.45 (per Aug 28, 2024. [data](https://datavista.bukitvista.com/queries/590?p_date=2024-04-01--2024-08-28#2177))

## Overall Rating
If we calculate the overall rating start from April 1, 2024 until August 28, 2024 the overall rating score is 4.77 (need 0.03 to achieve the SLA). But, if we calculate start from August 16, 2024 (the date when development finished) to August 28, 2024, the overall rating score is 4.84, means we're success achieve the SLA

![Image](https://github.com/user-attachments/assets/b2d93302-72ff-41aa-bb09-f8fbe2367b6d)

**Comment by Vidiskiu** [comment]
Overall Point: 4.9

Functional Complexity: 1.2

> Increasing the review conversion rate requires modifying existing flows and understanding user behavior, which adds significant functional complexity.

Technical Complexity: 0.8

> Integrating new messaging content and automating review request processes involve a moderate level of technical complexity.

UI/UX Complexity: 0.7

> Changes will be made to user-facing components, requiring consideration for UI/UX to ensure the messages are effective and encouraging for reviews.

Data Manipulation: 0.6

> The solution will necessitate manipulation of data, particularly with respect to automating tools and messages based on guest profiles and sentiment.

Testing: 0.2

> Testing is required to ensure the new systems work as intended and effectively improve the conversion rate.

Dependencies: 0.2

> Some dependencies on external messaging and analytics services are expected, but these are not substantial.

Risk and Uncertainty: 0.3

> There's a level of risk involved in terms of how users will respond to the new review request flow, but the uncertainty is relatively low.

User Impact: 0.9

> The change is directly targeted at users and has the potential to significantly impact their experience and the company's ratings.
