### ISSUE TITLE
Improve Thea's Likability 

### ISSUE THREAD

**Issue by rifqinvnd** [Bukit-Vista/roadmap#37]
# Description
This project aims to enhance Thea, the automatic auto-reply system for community management, by addressing existing issues and implementing new features. The improvements focus on optimizing performance, refining language delivery, and improving response accuracy, ultimately leading to better user experience and efficiency.

# Problem
Thea's current performance has several challenges, including slow loading times when displaying full conversations, inconsistencies in language delivery, and occasional errors in whitelist management, escalation status, and special instructions. These issues reduce Thea's effectiveness and could lead to suboptimal communication with property owners and staff.

# Solution
- Reduce Slow Loading: Address the slow loading times when opening the full conversation view, ensuring a more seamless and responsive experience.
- Implement Fine-Tuned Language Delivery: Introduce an experimental model for fine-tuning Thea's language delivery, making interactions more humanlike, warm, and engaging.
- Re-Adjust Whitelist, Escalation, and Special Instructions: Revise and refine Thea's whitelist criteria, escalation triggers, and special instructions to ensure they align with current needs and expectations.

# Measurement Objective
- Decision-Making Accuracy: Thea should accurately determine when to respond directly and when to escalate the issue to the relevant team.
- Forwarding Efficiency: Thea should effectively categorize and forward issues to the appropriate person in charge (PIC) with minimal errors.

# SLA
- Decision-Making Accuracy: Achieve 80% accuracy in Thea's ability to decide whether to reply or escalate.
- Forwarding Accuracy: Attain 80% accuracy in categorizing and forwarding issues to the relevant PIC.

# Team Member
@rifqinvnd @Ardy-BukitVista

**Comment by katibpasha** [comment]
Will be evaluated by @krisnaBukitVista

**Comment by krisnaBukitVista** [comment]
I’ve reviewed 128 samples and found that 102 messages had a good tone, 20 needed some tone improvement, and 6 had an improper tone. 

- Good Tone: 102 messages out of 128 samples, which is approximately 79.7%.
- Could Be Improved: 20 messages out of 128 samples, which is approximately 15.6%.
- Improper Tone: 6 messages out of 128 samples, which is approximately 4.7%.

The English responses have been excellent overall, but Thea still struggles with formulating Indonesian responses with the right tone. One major issue is Thea’s vocabulary in Indonesian; it tends to be overly formal, using terms like “terjaga,” “segera,” and “dukungan Anda.” This is largely because the resources for fine-tuning have been predominantly in English. We plan to address this by adding more references for Bahasa Indonesia to improve the tone and vocabulary.

**Comment by krisnaBukitVista** [comment]
For escalation accuracy, we’ve achieved a rate of 94.81% over the past 7 days, which is quite satisfactory.

**Comment by Vidiskiu** [comment]
Overall Point: 5.7

Functional Complexity: 0.9

> Optimizing Thea involves several aspects of the automatic response system which will elevate its functionality and positively affect user interactions.

Technical Complexity: 1.3

> Introducing a new experimental model for language delivery and refining core system functionality represent significant technical challenges.

UI/UX Complexity: 0.7

> Improving loading times and response interface will enhance the UX, but the main complexity lies in backend optimization rather than UI design.

Data Manipulation: 1

> Refining language delivery and criteria for escalation will involve complex data manipulation, including natural language processing and machine learning models.

Testing: 0.5

> Testing the improved areas thoroughly is crucial to ensure the new features perform reliably and makeup to the set standards (SLA).

Dependencies: 0.3

> While dependency on external models or services may be present for language processing, the task largely involves refining existing frameworks.

Risk and Uncertainty: 0.4

> Although critical for user satisfaction, the adjustments have a moderate risk, as they improve upon an already established system.

User Impact: 0.6

> Enhancements will significantly impact the user experience by providing faster and more accurate responses; however, the impact is somewhat limited to the scope of the auto-reply system.
