### ISSUE TITLE
Data Integrity for cancellation to reduce manual verification by exception handler

### ISSUE THREAD

**Issue by krisnaBukitVista** [Bukit-Vista/roadmap#39]
# Description
To minimize the manual effort required by exception handlers when checking cancellations and alterations, we aim to display only those cancellations that have data integrity issues.

# Problem
- Existing Automation: We already have an automation system in place for cancellation notifications. This system sends notifications to our Slack channel whenever there is a cancellation.
- Manual Verification Required: Despite the automation, the operations team still needs to manually verify the following:
  * Whether or not it is cancellation due to guest situation or out fault 
  * Whether or not the data integrity has been synchronized between Airbnb and BIGRR

# Solutions
We will develop a script in Google Colab to compare data between Beds24 and BIGRR. Any discrepancies will be displayed in the output, allowing exception handlers to focus solely on the exception list rather than reviewing the entire list of cancellations and alterations.

## Current Google Collab
- https://colab.research.google.com/drive/1jc2uhllM4cW571FBmGoK_i5sPNf3pb2j
- https://colab.research.google.com/drive/1YoxhATQK1XAc2MEaxw1kKDNIJA8TjrEa

# Measurement metrics
The primary metric for success will be the reduction in time required for exception handlers to check and skim through the cancellation channels.

# SLA
We will provide an output that lists bookings cancelled due to data discrepancies, thereby significantly reducing the time needed for exception handlers to identify and address these issues.

# Team Member 
@rifqinvnd  @Ardy-BukitVista

**Comment by katibpasha** [comment]
Will be evaluated by @katibpasha

**Comment by katibpasha** [comment]
## Evaluation Result

We already have gathered the data integrity validation for cancellation and alteration into one Google Colab file: https://colab.research.google.com/drive/12HkIA4KwD_zzrqSVkUOKXyRP73nmNrQy?authuser=7#scrollTo=sZoGlRUeB_aW

- User (exception handler) can get the lists bookings cancelled due to data discrepancies using this new script ![Image](https://github.com/user-attachments/assets/235e828b-7a70-4c3a-9993-b1eb9826e119)  ![Image](https://github.com/user-attachments/assets/40c18348-08a2-4860-919d-b79cc9409a7b)

**Comment by Vidiskiu** [comment]
- @katibpasha please conduct the demo for user and state limitation
- @krisnaBukitVista please start the next milestone iteration that handles Virtual Room + Handle unit not assigned in slack #--logs channel

**Comment by Vidiskiu** [comment]
Overall Point: 4.2

Functional Complexity: 0.7

> The project will enhance an existing function rather than create a new one, and focuses on filtering cancellations by specific criteria.

Technical Complexity: 0.8

> Involves writing scripts for data comparison, a task that requires a moderate level of technical skill but can be done with existing tools and APIs.

UI/UX Complexity: 0.5

> Improvements to an existing automation process do not involve significant UI/UX design changes but introduce some enhancements to how data is presented.

Data Manipulation: 0.9

> The task centers on data comparison, integrity checks, and discrepancy reporting, needing careful data manipulation.

Testing: 0.4

> Requires solid testing to ensure data integrity but is limited to a defined scope of data verification.

Dependencies: 0.3

> Depends on established tools such as Google Colab and data from Beds24 and BIGRR, but is an enhancement rather than a new setup.

Risk and Uncertainty: 0.3

> Involves some risk related to accurate data matching, but is low due to it being an improvement on an existing system.

User Impact: 0.3

> Directly impacts the operation team's efficiency, but the overall user experience may be indirectly affected through smoother operations.

**Comment by katibpasha** [comment]
> [@katibpasha](https://github.com/katibpasha) do we already have the task on backlog for handles virtual room and unassigned unit? CC: [@Vidiskiu](https://github.com/Vidiskiu)

Yes, we do. For virtual room handling is [here](https://github.com/Bukit-Vista/bv-internal-tools/issues/132) with Lutfi assigned as the programmer and unassigned unit is [here](https://github.com/Bukit-Vista/olympus-microservices/issues/1188) which has been completed by mas Wendy.

**Comment by katibpasha** [comment]
**Feedback from User**

- It's little bit confusing, because there are so many discrepancies data detected. It seems the date filtering hasn't been implemented yet
- Users expect to be able to adjust the date range themselves

@Vidiskiu @krisnaBukitVista
