### ISSUE TITLE
Iteration #2/Auto room assignment to avoid False OB

### ISSUE THREAD

**Issue by Vidiskiu** [Bukit-Vista/roadmap#40]
### Description
Continue improving the automation system for room assignment to further optimize room allocation and reduce false overbooking (OB) notifications. This iteration aims to address the remaining challenges and achieve the SLA target set in the previous milestone.

### Problem
The initial implementation reduced false OB notifications by 77%, but the SLA target of a 90% reduction was not met.
Unexpected behaviors such as late overbooking detection and frequent reassignment of rooms still occur.

### Solution

Refine Algorithms: Enhance the algorithms to better handle edge cases and further optimize room assignments.
Improve Detection Mechanisms: Implement more sophisticated detection mechanisms for double bookings and multiple guests assigned to the same room.
Address Late Detection: Tackle issues related to late overbooking detection and reduce the delay in identifying real overbooking cases.
Minimize Reassignments: Develop strategies to minimize the number of room reassignments to improve operational efficiency.

# Measurement Objective

Achieve a ratio of 1 false overbooking notification for every 10 valid notifications, as per the original SLA.

# SLA

Reach the target of a 90% reduction in false overbooking notifications. Evaluation period 2024-08-09 - 2024-08-19

# Evaluation
reviewed 30 samples during the evaluation period, and the algorithm successfully reassigned 27 cases, leaving only 3 as unresolved false overbookings. This shows that we've achieved the SLA, with a 90% reduction in false overbooking notifications.

# Prioritization result
- Relevancy: This task is highly relevant to our goal of automating operations, allowing the team to focus on more strategic work instead of manual, repetitive tasks.
- Feasibility: The algorithm for room assignments has been defined and tested, including scenarios with exceptions, proving that the task is achievable and ready to implement.
- Impact: By automating the process, we significantly reduce the need for manual checks on modified bookings, freeing up the team to tackle more critical issues and streamline operations.

### Team Member
@Zulfaabam @wendyyyanto

**Comment by katibpasha** [comment]
Will be evaluated by @krisnaBukitVista

**Comment by Vidiskiu** [comment]
Overall Point: 5.7

Functional Complexity: 1.2

> The task involves iterating on the existing system to handle complex edge cases, which requires understanding intricate business rules and system behavior.

Technical Complexity: 1.3

> Refining algorithms and improving detection mechanisms increase technical complexity, especially when addressing the minimization of false positives and unintentional reassignments.

UI/UX Complexity: 0.5

> The primary focus appears to be on the backend systems; however, there may be minor UI/UX considerations in presenting OB notifications more effectively.

Data Manipulation: 0.9

> Sophisticated manipulation of room and booking data is required to enhance the assignment algorithms and minimize errors.

Testing: 0.5

> Rigorous testing is needed to ensure that the refined algorithms meet the SLA targets and to validate that the rate of false OB notifications is under control.

Dependencies: 0.2

> There might be dependencies on the data sources and other internal systems, but since the basic framework is already in place from previous work, dependencies are relatively minor.

Risk and Uncertainty: 0.3

> While there is some inherent risk in changing the logic of operational systems, the task builds upon existing tested algorithms, reducing uncertainty.

User Impact: 0.8

> Improving room assignments and reducing false OB notifications have a significant impact on user experience and staff workload, but since it is a backend process, the direct impact on end-users is moderate.
