### ISSUE TITLE
Iteration #2: Personalized Hospitality Experience by providing events in the location proactively, integration with Website Event Calendar and Airbnb Guidebook

### ISSUE THREAD

**Issue by krisnaBukitVista** [Bukit-Vista/roadmap#42]
# Description
We aim to optimize the previous iteration, where we sent event details through the event calendar and guidebook to guests who first interacted with us. This iteration will ensure that all guests, regardless of their initial interaction, receive information about nearby events and attractions.

# Problem
- Currently, only guests who initiate contact with us receive event and location information, leaving others uninformed.
- We've identified that many guests are not receiving event and nearby attraction details, leading to a gap in our service.

# Solution
- Implement a scheduler that automatically sends notifications to guests who haven't communicated with us, ensuring they also receive event information.
- Integrate nearby attraction recommendations from the property listing so that all guests receive valuable suggestions during their stay.

# Measurement objective
- Improve the location rating for September 2024.
- Track the number of guests receiving event or nearby attraction recommendations.

# SLA
- Achieve a 78% location rating by September 2024.
- Ensure 100% of guests receive either event or nearby attraction recommendations.

# Team Member
@rifqinvnd @Ardy-BukitVista

**Comment by katibpasha** [comment]
# Evaluation Result

The development stage has been finished on Aug 17, 2024. Executed by Lutfi as programmer. 

## Location Rating
Rating from Apr 1, 2024 until Aug 16, 2024 is 73,2% 

![Image](https://github.com/user-attachments/assets/656245cf-d1f2-4ccd-8a98-a7c6fe42221b)

Then, the rating score for location starts from Aug 17, 2024 (when the features are released) until Aug 27, 2024 is increased to 76,6%

![Image](https://github.com/user-attachments/assets/fb3264e8-c1c7-4bcf-a73b-cdb51b91546b)

## Event Recommendation Logs

**Comment by Vidiskiu** [comment]
Overall Point: 5.6

Functional Complexity: 1

> Optimizing the event delivery system for broader coverage of guests adds significant functional complexity.

Technical Complexity: 1.1

> Technical aspects such as scheduling, integrating various data sources, and ensuring the reliability of notifications is complex.

UI/UX Complexity: 0.8

> Enhancing the UI/UX for better integration of the event calendar and guidebook with the primary service adds a fair level of complexity.

Data Manipulation: 0.9

> The challenge lies in manipulating and synchronizing data from different sources to provide relevant and personalized content to guests.

Testing: 0.3

> Testing is important to validate the reliability of notifications and data accuracy but does not involve excessive new protocols.

Dependencies: 0.3

> Some dependency on third-party services like event databases and Airbnb APIs may exist, but they are not expected to pose significant blocks.

Risk and Uncertainty: 0.2

> There's some uncertainty in how guests will perceive the new features and how much it will improve the location rating.

User Impact: 1

> The feature has a direct and significant impact on user experience by ensuring all guests receive a personalized and informative service.
