### ISSUE TITLE
Increase helpfulness in our main website using strategic visualization

### ISSUE THREAD

**Issue by krisnaBukitVista** [Bukit-Vista/roadmap#44]
# DESCRIPTION
This project focuses on improving the user experience on our main website by incorporating strategic visualizations that will provide deeper insights into Bali’s property landscape. We aim to enhance how users engage with the site by offering interactive tools that visually represent changes over time and highlight key areas of interest. The goal is to drive more informed decisions and boost user interaction by making the website more intuitive and visually appealing.

# PROBLEM 
Currently, users have limited access to dynamic, visual representations of property trends and changes over time. This lack of interactivity makes it difficult for them to grasp the evolving property landscape in Bali, hindering their decision-making process and potentially impacting our revenue streams from property-related programs.

# SOLUTIONS
- We will provide a time-lapse feature for each property area, allowing users to see the evolution and changes over time, giving them a clearer picture of market trends.
- We will implement a heatmap that highlights areas with a high distribution of great ratings, making it easier for users to identify prime property locations across Bali.

# MEASUREMENT METRICS
- Number of clicks and user navigation through the interactive heatmap.
- User approval to evaluate whether it fits their current expectation

# SLA 
- Number of Clicks/User Navigation on Interactive Heatmap: Target 50 unique user interactions per month. This accounts for lower traffic but emphasizes the importance of engaging users with the new feature.
- User provide positive testimony regarding the implementation on our website

# PRIORITIZATION RESULT 
- Relevancy: This project aligns with our broader program to boost revenue, though the precise impact remains difficult to measure at this stage.
- Feasibility: The time-lapse feature is feasible using Google Earth Pro, requiring only the pinpointing of specific coordinates. The heatmap, while requiring further research, has already shown promising progress in its initial stages.
- Impact: This initiative is expected to enhance our investment opportunities program. However, as the program is still new, it may be challenging to fully assess its impact at this time.

**Comment by katibpasha** [comment]
# Mid-evaluation Result

- There are several feedbacks from user (marketing team) that can we improve in current iteration or future milestone
    - Color palette can be adjusted to be more clear. Actually, this is not too necessary because users can change it by their own and we have provided the guidance in CODA
    - Add threshold in data display, so we only show bubble mapping with rating more than 4
    - Add legend to explain the meaning of bubble radius size and color (important)
    - Small refinement in third chart to be adjusted like second chart when user scroll down the cursor
- About the SLA, now we have achieved for 34 unique visitors of pages. And users said that actually for the user session duration is not necessary. They said that even only with this visualization it was enough. I think we need to re-adjust the SLA @krisnaBukitVista

**Comment by katibpasha** [comment]
Performance evaluation per Sep 18 2024:
![Image](https://github.com/user-attachments/assets/5c35e37e-05c2-4469-8c6b-fd07f8754153)

**Comment by katibpasha** [comment]
# Final Evaluation Result

Following up on user feedback, we have made the following adjustments
- Color palette of chart has been adjusted more clear
- Outliner data below threshold (4 rating) wouldn't show in visualization
- Legend section has been added to chart visualization
- Scroll down feature has been adjusted for the third chart

User has approved the project and it means we achieved one of this milestone's SLA. Then, the traffic report also has achieved the SLA.

**Comment by Vidiskiu** [comment]
Overall Point: 4.85
Functional Complexity: 1.5

> The project requires moderate level of functional complexity, introducing interactive tools like a time-lapse feature and a heatmap that must work cohesively within the user interface.

Technical Complexity: 1.75

> Incorporating dynamic time-lapse features and heatmaps is technically involved, requiring integration of external tools like Google Earth Pro and potentially complex data processing for the heatmap.

UI/UX Complexity and Impact: 1.25

> The visualization tools will significantly alter user interaction on the site, requiring thoughtful design and careful integration to ensure a seamless and intuitive user experience.

Testing and Quality Assurance: 0.35

> Testing for this feature includes verifying the user interactions with visualizations and ensuring the data is correctly represented, which is moderately complex.

Risk and Dependencies: 

>
