### ISSUE TITLE
Local cache / BV Go user experience improvements

### ISSUE THREAD

**Issue by krisnaBukitVista** [Bukit-Vista/roadmap#47]
# Description
This project focuses on enhancing performance to provide a smoother and faster user experience by reducing loading times when accessing dashboard page, booking page, and my property page

# Problem
Users are experiencing delays in accessing real-time data, causing frustration. Every time they switch between pages, there’s a noticeable lag in loading new information, which hampers their workflow and guest communication.

# Solutions
## Performance Optimization
- Local Data Storage: Cache previously fetched data locally so that when a user revisits the page, the older data is instantly available, reducing any loading time.
- Background Data Fetching: While the user views the page, updated data is fetched in the background with a small visual indicator, ensuring that the page automatically refreshes without needing a full reload. This method is inspired by apps like Slack, Coda, and Twitter.

## Pages to Implement Local Storage in BVGO
1. Dashboard Page
- Newsletter Section: Save details of every newsletter detail page that has been opened.

2. Booking Page
- Calendar Tab: Track and store each month that has been opened.
- Detail Booking: Store the state of the following tabs that have been opened within a guest's booking: Chat Tab, Journey Tab, and Reservation Tab

3. My Property Page
- Accounting Report: Store every monthly report that has been opened.
- Expenses: Store every monthly report that has been opened.
- List of Guest Reviews: Track and store every guest review that has been accessed.
- Detail Guest Review: Store details of every specific guest review that has been opened.

# Measurement metrics
- Page Load Time Reduction: Measure the decrease in perceived load times when switching between pages, aiming for a 50% reduction compared to the current performance.

# SLA 
- Page Load Reduction: Achieve a 50% reduction in perceived load times, ensuring faster data access for users.

**Comment by krisnaBukitVista** [comment]
user feedback: 
- gamify process in updating guest journey

**Comment by Vidiskiu** [comment]
Overall Point: 5.25
Functional Complexity: 1.5

> The project involves adding local caching for multiple pages which introduces several functional steps such as caching logic, background fetching, and auto-refresh, resulting in medium functional complexity.

Technical Complexity: 1.75

> Implementing local caching on different pages with background data fetching and visual indicators involve moderate technical work with some challenges in state management and ensuring seamless data synchronization.

UI/UX Complexity and Impact: 0.75

> The visual indicators and automatic refresh of pages entail moderate UI/UX updates without redesigning core flows, but with a focus on enhancing the user's perception of speed and fluidity.

Testing and Quality Assurance: 1

> Testing will be needed to validate the local data storage and background fetch implementations. This includes measuring performance improvements and ensuring that cached data is updated appropriately, constituting a medium level of testing complexity.

Risk and Dependencies: 0.25

> There seems to be a low level of risk and dependencies as the requirements are clear, but still some risk is present due to the need to maintain consistent performance across different parts of the application.
