### ISSUE TITLE
Feed - AION as agent specialized for content creator and distributor

### ISSUE THREAD

**Issue by krisnaBukitVista** [Bukit-Vista/roadmap#48]
# Description
This project is focused on improving both BVGO adoption and partner engagement through two key initiatives: first, by integrating essential operational activities from Hubspot into BVGO, and second, by enhancing our relationships with property owners through personalized notifications that celebrate key milestones. We are also introducing a new agent, Aion, inspired by the Hellenistic deity associated with time and the universe, who will specialize in crafting engaging content for these initiatives. These efforts will boost transparency, streamline communication, and foster stronger connections with our partners.

# Problem
Currently, there is a lack of seamless communication and display of key operational activities for partners within BVGO. Additionally, our communication with property owners has been largely operational, leaving significant moments unacknowledged. This creates gaps in both transparency and personal connection, which can hinder partner trust and engagement.

# Solution
- BVGO Adoption through Hubspot Integration:
We will integrate PEST control activities, inspection schedules, and offline hosting information from Hubspot into BVGO to provide partners with a more comprehensive view of their operations.
- Personalized Celebrations and Notifications for Key Moments:
We will implement automated notifications that celebrate Bali’s cultural events and key owner milestones (guest counts, review achievements, contract anniversaries, and revenue milestones).
Aion, our content creator agent, will be responsible for personalizing these messages, ensuring that each interaction feels meaningful.
- Data Visualization for Partnership Team:
We will develop a dashboard for the internal team to track and prepare for special moments, as well as ensure that the integration of Hubspot activities is fully functional and beneficial for partners.

# Measurement Metrics
- BVGO Integration Metrics:
a. Ensure Hubspot activities are accurately reflected in the BVGO newsletter and accessible to partners.
b. Gather approval or positive feedback from partners regarding the integration’s usefulness.

- Partner Engagement Metrics:
a. Track the effectiveness of Aion’s personalized content through partner responses.
b. Monitor the accessibility and usage of the dashboard for upcoming celebrations.

# SLA
- BVGO Integration SLA:
a. The integration should function seamlessly with no technical issues.
b. More than 50% of partners should provide positive feedback on the integration’s impact.

- Partner Celebration SLA:
a. The dashboard should be live and accessible via Datavista.
b. Notifications should be automatically sent, and all content must be personalized by Aion according to partner preferences.

# Prioritization result
- Relevancy: The integration is critical for building transparency and trust with partners, while the personalized celebrations help strengthen long-term relationships.
- Feasibility: The integration is feasible with API and data syncing methods, and Aion’s role in content creation aligns with existing tools for automated notifications.
- Impact: The integration will enhance partner trust and satisfaction, and the personalized notifications will further foster a sense of connection, reducing the likelihood of offboarding.

# Team Member
@RobinNusantara

**Comment by krisnaBukitVista** [comment]
## Owner Key Moment Celebration Plan:

1. Bali Celebrations
- Celebrate Bali’s cultural and traditional events (e.g., Galungan, Nyepi).
- Notification timing: On the day of each celebration.
- Message content: Include warm wishes tied to the cultural significance of the event.

2. Guest Milestones
- Celebrate reaching key guest milestones (e.g., First Guest, 100 Guests, 300 Guests, 500 Guests, 700 Guests, 900 Guests, etc).
- Notification timing: Automatically triggered on the day each milestone is achieved.
- Message content: Congratulate the owner with enthusiasm.

3. Review Milestones
- Celebrate review milestones (e.g., First Review, 100 Reviews, 300 Reviews, 500 Reviews, 700 Reviews, 900 Reviews, etc).
- Notification timing: Triggered on the day the milestone is achieved.
- Message content: Acknowledge their hard work and positive feedback.

4. Contract Anniversary
- Celebrate the owner’s contract anniversary.
- Notification timing: On the anniversary date.
- Message content: Express appreciation for their partnership and reflect on the past year(s).

5. Staff and Owner Birthdays
- Send personalized birthday greetings.
- Notification timing: On the birthday date.
- Message content: Share warm birthday wishes and appreciation.

6. Revenue Milestones
- Celebrate revenue milestones (e.g., 1K, 10K, 100K, 1,000K in revenue).
- Notification timing: Automatically triggered on the day of the milestone.
- Message content: Celebrate their financial success and offer encouragement.

## Data Visualization
A dashboard will be provided to the partnership team, showing upcoming special moments so they can better prepare or engage when needed.

# Measurement Metrics:
- Accessibility of the dashboard to the internal team.
- Newsletter functioning as a notification system without the need for human operations.
- Personalized language tailored to user preferences in the notifications.

# SLA 
- The dashboard must be live and accessible in Datavista.
- Newsletters are sent automatically with no manual intervention.
- All newsletters are personalized according to user preferences.

**Comment by krisnaBukitVista** [comment]
## SOLUTIONS
- Integrate PEST control activities from Hubspot into BVGO for easy tracking by partners.
- Sync inspection schedules from Hubspot to BVGO so partners can view them directly in the system.
- Display relevant information such as offline hosting details in BVGO for partner reference.

## MEASUREMENT METRICS
- The information from Hubspot is reflected in the BVGO calendar, accessible to partners.
- We receive approval or positive feedback from partners regarding the usefulness of the integration.

## SLA
- The feature is successful and functions without bugs or technical issues.
- More than 50% of partners provide positive feedback or appreciation for the integration.

**Comment by krisnaBukitVista** [comment]
[content for aion.pdf](https://github.com/user-attachments/files/16744162/content.for.aion.pdf)

**Comment by bstiawan** [comment]
Project evaluation:

- Lack of vision to execution alignment
  - The workflow to create an agent is unclear from the beginning, there's confusion:
    - What needs to be delivered first and tested
    - What can wait for later stage of development
    - How to divide between dependency task and modular task
    - Unclear release train schedule, too many delays
  - Insight from MVP is not communicated, instead Lutfi need to recreate from the beginning
  - AI knowledge is not transferred 
    - Initially the development is approached as functional engineering where we write code for each case, not AI engineering where the AI can take a different input and give relevant output without writing all cases
- Low ownership
  - Executors didn't understand what needs to be delivered and not discovering issues
    - Robin didn't understand that the complete agent functionality needs to be delivered first, and the input is modular. He should understand that he's serving other developers that will be working on the key moment trigger.
    - The agent didn't have debugging tool to see the input vs output
  - PO

**Comment by katibpasha** [comment]
# Final Evaluation Result

Today, I've started to contact partners to ask for their feedback. From 30 partners I've contacted, it's only 5 partners gave response. So, we'll extend the evaluation to Oct 2.

Partner list: https://docs.google.com/spreadsheets/d/1-02uQNSEpqNn-dKBvTyOss4hDs3rGII4e-KDEf8yrFA/edit?gid=0#gid=0

cc @Vidiskiu @krisnaBukitVista

**Comment by Vidiskiu** [comment]
Overall Point: 5.25
Functional Complexity: 1.5

> The project encompasses a variety of functional steps, such as integrating HubSpot activities into BVGO and automating personalized notifications, which introduces moderate complexity.

Technical Complexity: 1.5

> Technical complexity is moderate due to the need for API integration with Hubspot and data syncing, but the issue description indicates that feasible methods are already considered.

UI/UX Complexity and Impact: 0.75

> Mid-level UI/UX complexity is anticipated for implementing the dashboard and ensuring notifications are well-received by users, which will affect the partner's interaction experience.

Testing and Quality Assurance: 1

> Substantial testing is required to verify integration accuracy and personalization effectiveness. However, it isn't the highest complexity as metrics and SLAs are clearly defined.

Risk and Dependencies: 0.5

> Risk appears to be moderate with well-defined SLAs and a focus on partner feedback, but the project's dependency on HubSpot API and partner data introduces some uncertainty.
