### ISSUE TITLE
Badge - Ranking and leaderboard for partner digital token of achievements

### ISSUE THREAD

**Issue by krisnaBukitVista** [Bukit-Vista/roadmap#50]
# DESCRIPTION
 This project involves developing a monthly evaluation and ranking system for properties based on review conversion rates and occupancy rates. The properties are divided into five leagues, each represented by a specific badge: Diamond, Platinum, Gold, Silver, and Bronze. The ranking is localized within each league, and properties are awarded badges based on their final rank at the end of the evaluation period

# PROBLEM 
- We rarely celebrate our achievement, partner only contact us for complaining issue and problem 
- We want to shape narrative that we also did something wonderful to them

# SOLUTIONS
- We will create four badge tiers: Diamond, Platinum, Gold, Silver, and Bronze.
- Criteria and classification rules for each badge tier will be clearly defined.
- The badge placement and design will be integrated into BVGO, ensuring visibility and alignment with the platform’s aesthetics.
- There should be ranking visualization for each badges so each property understand their position

## Badges Criteria 
 - DiamondLeague: Ranks 1-25 (25 members)
 - Platinum League: Ranks 26-50 (25 members)
 - GoldLeague: Ranks 51-75 (25 members)
 - Silver League: Ranks 76-100 (25 members)
 - BronzeLeague: Rank 101 and above

## Evaluation Criteria
- Metrics: Properties are ranked based on two key metrics:
 a. Overall hospitality rating: Scored from 0 to 10 based on the percentage
 range of hospitality rating.
 b. OccupancyRate: Scored from 0 to 10 based on the percentage range of
 occupancy rates.
- Weighting: The overall rating and booking occupancy rate are weighted equally (50% each) in the final score calculation.

## Evaluation Process
- Monthly Evaluation: Rankings are finalized at the end of each month.
- Ranking Localization: Properties are ranked within their respective leagues, and each league has a top rank (e.g., Rank 1 in Gold League).

## Display Criteria
- Rank Display: Only the property name and rank are displayed.
- Limited Display: Display only the five ranks higher and five ranks lower around a property’s position in the league. No numbers or points are shown.
- Comparison: Display an up or down arrow next to the rank to indicate movement compared to the previous evaluation.
- Reporting: Detailed reports explaining the reasons for rank changes are sent to the properties, with all numerical data hidden from the on-screen display.
a. Daily ranking update: daily up and down --> push notification in mobile app. Always process on 8 AM in the morning. 
b. League update: uprank or downrank --> create newsletter / push notification in mobile app. Process on 9 AM in the morning. 
c. Month ranking finalization: final ranking --> occupation rate and hospitality score (cleanliness, value, communication, etc)

## Limitations
- League Visibility: Properties can only see rankings within their own league; cross-league visibility is restricted

## MVP
https://datavista.bukitvista.com/queries/1067?p_date=d_this_month

# MEASUREMENT METRICS
- The badge feature is fully operational on BVGO.
- The accuracy of badge assignments, ensuring they reflect the correct partner achievements.

# SLA
- The badge feature must function smoothly without any errors on the partner's end.
- The badges must consistently and accurately reflect partner achievements according to the pre-defined criteria.

# Team Member
@wendyyyanto

**Comment by krisnaBukitVista** [comment]
[Implementing Badges in BVGO.pdf](https://github.com/user-attachments/files/16775499/Implementing.Badges.in.BVGO.pdf)

**Comment by krisnaBukitVista** [comment]
Project met the designed SLA, however, we got request to reconstruct the leaderboard to show nuance partner against themselves.

**Comment by Vidiskiu** [comment]
Overall Point: 5.5
Functional Complexity: 1.5

> The project includes a multi-tiered ranking and badge assignment system, which requires complex logic to handle different evaluation criteria and league localization, but does not include highly intricate business logic across multiple user flows.

Technical Complexity: 2

> The system requires integration with existing databases, potentially new backend logic to process rankings, and scheduling tasks for notifications. The complexity is increased due to the need to perform evaluations and updates at specific times.

UI/UX Complexity and Impact: 1

> Significant UI/UX work is needed to integrate badge placement, ranking visualizations, and ensure the design is consistent with the platform's aesthetics. This also includes designing clear and meaningful visualizations for the badges and ranks.

Testing and Quality Assurance: 0.75

> Moderate to extensive testing is required to validate the correct functioning of the ranking algorithms, UI elements, and scheduled notifications. However, since the functionality is self-contained and there's a clear MVP, the testing is less extensive than for entirely new platforms.

Risk and Dependencies: 0.25

> The risk and dependencies are low because the project seems to build upon existing metrics and platforms, and the requirements are well-defined.
