### ISSUE TITLE
improve guest experience through paramount memorization as guest profile.

### ISSUE THREAD

**Issue by krisnaBukitVista** [Bukit-Vista/roadmap#56]
# DESCRIPTION
The project focuses on improving guest engagement by creating a selective memorization system that fetches conversation data to store and utilize key guest details. The system will automatically label whether the information is attached to the guest or the booking, allowing for more accurate insights. The goal is to provide personalized recommendations, enhance communication, and drive actions such as upselling or generating guest lists for the awareness team to curate.

# PROBLEM 
- There is no systematic approach to memorizing and utilizing guest conversation data.
- The lack of selective memorization leads to missed opportunities for personalized communication and actionable insights, which can affect communication quality, guest engagement, and upselling potential.

# SOLUTIONS

## Build selective memorization 
by verifying which guest or booking details are important to remember and which are not, ensuring only critical information is stored.

## Fetch and summarize guest conversation guest profiles 
to capture valuable insights and automatically label the information based on whether it is related to the guest or the booking.

## Utilize collected data for three actionable outcomes:
- Provide personalized recommendations.
- Generate guest lists for the awareness team, who will manually curate potential RTT guests.
- Upsell other properties based on guest preferences.

# MEASUREMENT METRICS
- Reliability of the memorization mechanism.
- Improved communication quality, as indicated by an increase in communication rating.

# SLA
- Gaia should memorize the information correctly, with a reliability rate of at least 80%.
- Increase the monthly communication rating 1% from previous month
   - 2024-11-01: To speed evaluation, we expect 0.3% increase by 2024-11-11

# Team Member
@Ardy-BukitVista

**Comment by krisnaBukitVista** [comment]
Mid Evaluation Summary (Oct 20th)

- We have conducted a test using 5 sample guest messages to evaluate the memorization process. Here are the key observations:
- Straightforward Messages: When guests provide clear and direct information in their messages (e.g., personal details, job-related data), the system’s memorization works excellently in capturing and retaining the critical insights.
- Implicit Messages: However, when the information is communicated more subtly or indirectly, the memorization process does not perform optimally in extracting and identifying the key insights.

Actionable Steps:
- Adjust Prompting: Modify the prompts to better identify and extract implicit insights, ensuring that subtle cues and indirect information are effectively recognized and stored.
- Refine Guest Persona Definitions: Enhance the guest persona definitions by including a broader set of critical memory points that capture relevant information, helping improve the understanding of what to memorize.

**Comment by krisnaBukitVista** [comment]
sample testing 

- "Hi, I just arrived at the property, and I’m having trouble getting the Wi-Fi to work. I really need it for a video call with my team back in New York. Can you help me with the network details?"
- "I wanted to check if there’s a possibility for an early check-in tomorrow. My flight arrives at 6 AM because I’m traveling from Europe after a long business trip, and I’d love to get some rest before my meeting.
- "Can you recommend some local restaurants or cafés nearby? I’m here celebrating my anniversary, and we’d love to have a nice romantic dinner."
- "We had a great stay! Everything was perfect. My daughter loved the backyard space, and we even managed to get some family photos. Thank you for helping make our vacation special."
- "My check-out time is approaching, but I still have some work to finish. I’m a freelancer, and my deadlines are tight. Is there any chance I could get a late check-out?"

**Comment by krisnaBukitVista** [comment]
testing result 

{'analysis': 'The guest has just arrived at the property and is experiencing issues connecting to the Wi-Fi, which is crucial for a video call with their work team in New York. This indicates an amenity issue.', 'memorization': True, 'attached_to': 'booking', 'persona_definition': 'Amenity issue', 'summary_of_memorization': 'Guest had an issue with connecting to the Wi-Fi upon arrival, which was important for a video call with their team in New York.', 'new_persona_definition': None}

{'analysis': 'The guest is requesting an early check-in due to their flight arriving at 6 AM after a business trip from Europe. They need rest before attending a meeting, indicating the importance of accommodating their request to ensure a good experience.', 'memorization': True, 'attached_to': 'booking', 'persona_definition': 'Arrival time coordination', 'summary_of_memorization': 'The guest is arriving from Europe at 6 AM for a business trip and has requested an early check-in to rest before a meeting.', 'new_persona_definition': None}

{'analysis': 'The guest is asking for recommendations for local restaurants or cafés that are suitable for a romantic dinner, implying a celebration of their anniversary. The context is about planning a special event with a significant other during their stay.', 'memorization': True, 'attached_to': 'booking', 'persona_definition': 'Restaurant you liked', 'summary_of_memorization': 'The guest is celebrating an anniversary and is looking for a romantic dinner venue nearby. Suggesting a local restaurant or café that provides a romantic ambiance could enhance their stay.', 'new_persona_definition': None}

{'analysis': 'The guest, who is a freelancer with tight deadlines, is requesting a late check-out to finish work before leaving. This indicates their work-related need for flexibility during their stay. The request relates to specific booking arrangements and also highlights their occupation as a freelancer.', 'memorization': True, 'attached_to': 'guest and booking', 'persona_definition': 'Occupation', 'summary_of_memorization': 'The guest is a freelancer with tight deadlines and requests flexibility for a late check-out to finish work.', 'new_persona_definition': None}

{'analysis': \"The guest expresses satisfaction with the stay, specifically highlighting the backyard space as a favorite spot, particularly enjoyed by their daughter. The mention of taking family photos suggests a memorable family moment during the vacation. However, there is no detail regarding amenity issues or specific personal information about the guest's life beyond the vacation memory.\", 'memorization': False, 'attached_to': None, 'summary_of_memorization': None, 'persona_definition': None, 'new_persona_definition': None}

**Comment by krisnaBukitVista** [comment]
Evaluation Summary (Nov 31st)

The issues highlighted during the mid-evaluation phase have now been successfully addressed. Specifically:
- Resolved Issues: Key concerns raised at the mid-point have been effectively resolved, enhancing the project’s overall stability and performance.
- Refined Guest Persona Definition: We have made significant improvements in defining guest personas, focusing on capturing and storing critical information. This refined approach enables us to better tailor our responses and interactions, aligning them more closely with guest needs and expectations.
- Improved Knowledge Memorization: Testing has shown marked improvement in our ability to retain implicit knowledge. This allows us to store nuanced details effectively, fostering a deeper understanding and continuity in guest interactions.

**Comment by Vidiskiu** [comment]
Overall Point: 5.5
Functional Complexity: 1.5

> Creating a selective memorization system involves multiple functional steps like verification of details, storage, and labeling, leading to moderate complexity.

Technical Complexity: 2

> The technical implementation requires intelligent data processing and integration with existing systems to fetch and summarize conversation data, which is complex.

UI/UX Complexity and Impact: 0.5

> While the back-end system is more complex, the UX improvements seem to be focused on the outcome rather than on UI changes, hence a lower UI/UX score.

Testing and Quality Assurance: 1

> Robust testing will be needed to ensure the reliability of the memorization mechanism and improvements in communication quality, demanding both unit and integration tests.

Risk and Dependencies: 0.5

> Though dependent on reliable data processing and accurate labeling, targeted SLAs imply that risk is moderated through incremental benchmarks.

**Comment by krisnaBukitVista** [comment]
Final Evaluation 

Memory Quality Checking 
- first sample: capable to detect repeat booking
![Image](https://github.com/user-attachments/assets/f40a41f6-b5a0-4d05-92db-40215bd4f204)
- second sample: capable to memorize hospitality issue 
![Image](https://github.com/user-attachments/assets/3936aeba-c1fd-4e6a-bafe-10ec55cd1c6b)
- third sample: capable to memorize guest schedule and rundown 
![Image](https://github.com/user-attachments/assets/91317c1f-abf5-4783-bd76-28c6605f34a7)
- fourth sample: capable to memorize guest health condition and their family 
![Image](https://github.com/user-attachments/assets/316dec7a-2b2e-4e2e-98e6-579b06513006)
- fifth sample: capable to handle resolved issue and guest feeling 
![Image](https://github.com/user-attachments/assets/40969e97-48f3-4ff3-8934-d496937b40e2)

**Comment by krisnaBukitVista** [comment]
Final Evaluation for Communication Rating 
![Image](https://github.com/user-attachments/assets/84971d97-0e4d-4519-976b-694e9befff07)
![Image](https://github.com/user-attachments/assets/8871bcbc-9643-4aa0-93d6-f826382278b8)
