### ISSUE TITLE
Hospitality / 100% message from WA, IG, FB classified and forwarded correctly to user

### ISSUE THREAD

**Issue by bstiawan** [Bukit-Vista/roadmap#6]
# Description
- The task involves integrating GAIA's auto-reply functionality with Sendpulse, replacing the previously used ManyChat, to optimize the communication processes across various platforms for different target audiences.
- Manychat lacks the necessary feature to be integrated to Hermes, being it's lacking ability to get full conversation and incomplete webhook.

# Problem
1. The current system lacks a robust integration of auto-reply functionalities through GAIA for managing communications across multiple audience types and platforms.
2. We still require intense resource operations in manychat.

# Solutions
- Implement Sendpulse and Hubspot as the WhatsApp API client to streamline the messaging process on Instagram, WhatsApp, and Facebook for different audience groups including confirmed guests, unconfirmed guests, partners, and prospective partners.

# Measurement metrics
- Resource allocation in Shift Management for Manychat or simillar platform
- Rate of message forwarded to user in Slack with Hermes Integration.
- Tool error rate

## Current measurements:
- Resource allocation in Shift Management for Manychat or simillar platform = 1
- Rate of message forwarded to user in Slack with Hermes Integration: No current measurements
- Tool errro rate: No current measurement

## SLA
- [x] Resource allocation in Shift Management for Manychat or simillar platform: 0
- [ ] 100% accuracy in categorizing user type and forward it correctly to the respective agent
- [x] tool error rate <15%

# Project Evaluation
You can check the sample [here](https://docs.google.com/spreadsheets/d/11N2ZcoXbY-904RymRWOZ6bve13w8wW0NJe4epwGVNvQ/edit?gid=0#gid=0)

- ManyChat Management:
Currently, we have no dedicated person to handle ManyChat.

- Tool Error Rate:
We encountered 1 error out of 20 samples, resulting in an error rate of 5%.

- User Type Categorization Accuracy:
We made 6 mistakes out of 20 samples, leading to an accuracy of approximately 70%.

Team member:
- @rifqinvnd

**Comment by krisnaBukitVista** [comment]
Update June 30th 

We failed to deliver the project on the initial deadline which is June 30th. Currently we are adjusting the project deadline to July 8th 
- this provides time for everyone to backup important number that might get erased during migration process
- extra time for continuing slight development after code review process
- also extra time for evaluation process

**Comment by Vidiskiu** [comment]
Overall Point: 4.9

Functional Complexity: 1

> Integrating a new system to replace an existing one involves considerable changes to the current workflow, requiring adequate adaptation and functionality adjustments.

Technical Complexity: 1.1

> Technical challenges include integrating with Sendpulse and Hubspot, dealing with multiple APIs, and ensuring correct message classification and forwarding across different platforms.

UI/UX Complexity: 0.4

> Minimal direct UI/UX complexity as the main focus is on backend integrations, but there is still some need to ensure a smooth user experience for managing communication processes.

Data Manipulation: 0.8

> The task will involve substantial manipulation of message data, categorization, and routing which requires careful handling and processing.

Testing: 0.5

> Given the integration's high impact on communication efficiency, thorough testing is essential, maxing out the score within its range.

Dependencies: 0.3

> Some dependencies are likely, particularly on third-party platforms' APIs, but these are expected and manageable within the scope of the project.

Risk and Uncertainty: 0.1

> While there is always some risk in integration projects, the use of established platforms like Sendpulse and Hubspot mitigates major uncertainties.

User Impact: 0.7

>
