### ISSUE TITLE
Improve flow of extra service

### ISSUE THREAD

**Issue by krisnaBukitVista** [Bukit-Vista/roadmap#61]
# Description 
This project aims to improve the management of extra services by leveraging our existing guest portal for driver-related services and streamlining communication for non-driver services. The focus is on reactivating the guest portal for driver coordination and ensuring accurate delivery of vendor contact information for other services.

# Problem
- Driver Comfort with Guest Portal: Drivers are more comfortable using the guest portal, and we already have a well-established system to support this.
- Low Reliability in Sending Vendor Phone Numbers: The current mechanism for sending vendor contact information (outside of driver services) has a low reliability rate, causing inefficiencies and delays.

# Solution
- Guest Portal for Drivers Only: We will reactivate the guest portal exclusively for managing driver requests to enhance the user experience and improve coordination.
- Vendor Contact Information for Other Services: For non-driver-related extra services, we will streamline the process by sending vendor phone numbers directly to guests, reducing liability and simplifying the process.

# Measurement Metrics
- Successful Use of Guest Portal for Driver Requests: The guest portal will be used effectively for coordinating driver services.
- Success Rate for Accurate Vendor Phone Numbers: Track the percentage of successfully sent and accurate vendor phone numbers for non-driver extra services.

# SLA
- Guest Portal for Driver Requests: Ensure 100% successful use of the guest portal for driver-related service requests.
- 90% Success Rate: Achieve a 90% success rate in sending accurate vendor phone numbers for extra services outside of driver coordination.

**Comment by katibpasha** [comment]
# Final Evaluation Result

1. Here is the message's response history related to guest's driver request: https://docs.google.com/spreadsheets/d/1h9uhWgmf6v9gpv_Bj4L8DWQL718uFyW4hU9bnoOkroM/edit?gid=0#gid=0
From 15 log samples, all of those successfully sent related driver's Whatsapp number

2.

**Comment by Vidiskiu** [comment]
Overall Point: 4.75
Functional Complexity: 1.5

> The project requires integrating existing services with the guest portal and ensuring accurate communication channels. Functional complexity is moderate due to the need for condition-based logic for different service types.

Technical Complexity: 1.5

> Technical effort is moderate for reactivating and integrating the guest portal with the current system. However, sending vendor information accurately might require careful handling of data which adds to the technical challenge.

UI/UX Complexity and Impact: 1

> The UI/UX changes involve reactivating a portal but also streamlining user interactions for non-driver services, which equates to a moderate UI/UX complexity affecting user behavior.

Testing and Quality Assurance: 0.5

> Requires standard testing for the update of the guest portal and the delivery mechanism of vendor contact information. Will involve some integration testing, but the scope is limited to the pre-existing system.

Risk and Dependencies: 0.25

> Low risk and few dependencies are involved since the system is well-established and the changes are mostly internal, without significant reliance on external systems or APIs.

**Comment by katibpasha** [comment]
# Functionality Test

Successfully tested on https://guest.bukitvista.com for the Airport and Car Pick-up service.
- The request history stored in booking detail
- Guest able to request extra service on Guest Portal
- Guest able to cancel the request

![Image](https://github.com/user-attachments/assets/5aa680d2-2376-48bc-b080-dbcee344b695)
