### ISSUE TITLE
Communication framework that delivers difficult news to partners

### ISSUE THREAD

**Issue by krisnaBukitVista** [Bukit-Vista/roadmap#66]
# Description
This project focuses on automating the delivery of bad news to partners regarding two key performance aspects: revenue and review contribution. Using newsletter, partners will be proactively notified of underperformance, such as a listing suspension due to bad reviews or failure to meet revenue targets based on the business plan. This proactive approach is designed to maintain transparency and trust with our partners.

# Problem
Partners are often unaware of underperformance issues with their listings until it significantly impacts their business, leading to dissatisfaction and a potential loss of trust. Without timely communication, partners may be caught off guard by issues such as low review ratings or unmet revenue targets, resulting in strained relationships.

# Solutions

## [Revenue Notifications](https://docs.google.com/spreadsheets/d/16YhzPTSXQRZfpQ4m8Gg9kxMP4V2NJAxMPqerzl70j5c/edit?usp=sharing)
- Partners will be notified if their popularity of listing is dropping. Listing popularity dropping are indicated with 2 factors (weekly booking pace less than 2 and next occupancy rate <= 40%)
- Partner will be notified if available time is not enough to fill the target signed.

## Review Notifications 
- Partners will be notified if their listing is suspended due to receiving a bad review.
- Partners will be notified if they receive three consecutive bad reviews, defined as an overall rating below 5 stars with bad score on sentiment 
- Partners will be notified if they receive overall rating of 1 star

## Automated Notification via Newsletter
Thea will automatically fetch the relevant data and notify partners when their performance in either revenue or reviews falls below the thresholds.

All newsletters should align with company branding and contain:
- Current Problem: Clearly outline the main issue or challenge being addressed.
- Our Team’s Actions: Highlight the proactive steps our team is taking to resolve it.
- Engagement Question: Ask recipients if they agree with our approach or prefer no action—giving them a sense of control and choice.

# Measurement Metrics
- Performance Tracking: Thea will accurately fetch properties with underperformance in both review and revenue.
- Notification Accuracy: Thea will deliver bad news notifications based on real-time data, ensuring that partners are informed of issues immediately.

# SLA (Service Level Agreement)
- Data Accuracy: Thea will accurately fetch properties underperforming in reviews and revenue with a 100% success rate.
- Timely Notifications: Thea will forward bad news notifications to partners immediately upon identifying underperformance, ensuring real-time communication.
- Notification Accuracy: Thea will deliver accurate notifications 100% of the time based on real performance data.

# Evaluation (Nov 8th) 
Based on the given SLA, I have reviewed five samples and found that data accuracy, timely notifications, and general notification effectiveness are on point. The system is meeting its functional goals as outlined in the SLA; however, it is still not fully optimal in delivering the intended branding touchpoints.

Currently, we have a strong emphasis on demonstrating how the system's actions work, which helps clarify functionality and usage. However, the branding element, specifically the emphasis on positioning us as the "hero" or primary protagonist, is still minimal and not as impactful as intended.

Key feedback
- when showing the decline, ensure that it gives feeling of security 
- never give the action to owner such as "review your promotional strategy", it's on us, not owner
- emphasize that we are hero to save the day
- emphasize our sidekicks about what engineering, marketing, operational, and revenue team will do to solve the case

**Comment by krisnaBukitVista** [comment]
user feedback: 
- quarterly much better 
- below 5 stars with bad sentiment

**Comment by krisnaBukitVista** [comment]
revenue calculation: 
https://docs.google.com/spreadsheets/d/16YhzPTSXQRZfpQ4m8Gg9kxMP4V2NJAxMPqerzl70j5c/edit?gid=0#gid=0

**Comment by Vidiskiu** [comment]
Overall Point: 6.25
Functional Complexity: 2

> This issue is complex as it involves automating the process of identifying underperformance and triggers for communication. It includes logic to analyze performance metrics, identify when conditions are met for delivering bad news, and manage different scenarios for revenue and review contribution.

Technical Complexity: 2

> The technical implementation requires data fetching, integration with an automated newsletter system, conditional triggers based on the fetched data, and ensuring high data accuracy and real-time notification delivery, which increases the technical complexity.

UI/UX Complexity and Impact: 1

> Creating an automated newsletter that aligns with company branding and contains various components such as problem statements, actions taken, and engagement questions adds considerable UI/UX complexity, as it heavily impacts how partners perceive the communication.

Testing and Quality Assurance: 1

> This requires comprehensive testing to ensure that notifications are accurate, timely, and align with the factors outlined (like weekly booking pace and occupancy rate for revenue, and bad review criteria for listings), as well as SLA metrics like data accuracy and notification timeliness.

Risk and Dependencies: 0.25

> There may be a low level of risk and few dependencies since the project seems to have a contained scope and relies on internal data, but there are uncertainties in perfecting the branding touchpoints and partner perception.
