### ISSUE TITLE
Enhance calendar blocking system for efficient management

### ISSUE THREAD

**Issue by krisnaBukitVista** [Bukit-Vista/roadmap#67]
# Description 
Based on feedback from the partnership team, this project aims to improve the calendar blocking process for both partners and internal employees. The focus is on enhancing flexibility, communication, and clarity. The two primary areas of improvement are:
- Increasing flexibility for internal employees, particularly in maintenance-related calendar blocking.
- Adding more detailed options for partners to categorize blocks made for personal use.

# Problem 
Currently, the blocking calendar process lacks sufficient communication and clarity, which leads to confusion between internal teams and partners. Internal employees cannot provide detailed information when blocking for maintenance, and partners are unable to categorize personal blocks, which complicates coordination and planning.

## Internal Employee Challenges:
- No way to attach important information (e.g., images, notes) when blocking dates for maintenance.
- Lack of clarity leads to misunderstandings with partners about the nature and duration of the block.

## Partner Challenges:
- Partners can block dates but cannot specify if it’s for personal reasons (e.g., selling the property, personal occupancy), making it difficult to understand their intentions.
- This ambiguity reduces efficiency and disrupts planning across teams.

# Solution:

## Internal Employee Flexibility Improvements:
- Introduce a new feature allowing internal employees to attach additional details, such as text notes or images, when blocking calendars for maintenance purposes.
- This will improve communication with partners by providing more transparency about the scope, duration, and type of maintenance.
- Add communication field that enable discussion between partnership team and partner 

## Partner Blocking Details for Personal Use:
- Provide partners with user-friendly options to categorize calendar blocks for personal use.
- Categories may include reasons like selling the property, use by relatives, or personal/owner occupancy. This will enhance clarity and coordination, ensuring internal teams are better informed about the nature of the block.

# Measurement metrics
- Percentage of maintenance blocks where internal employees attach text details or images.
- Rate of successful communication through the maintenance block feature (based on feedback or usage).
- Percentage of personal use blocks where detailed information is fetched and visualized for the internal team.

# SLA
- Ensure 100% functionality of attaching text details and images to the maintenance block with no errors during usage.
- Ensure 100% functionality of the communication feature through the maintenance block without error.
- Ensure 100% accuracy in fetching and visualizing detailed information behind personal use blocks for the internal team without errors.

**Comment by katibpasha** [comment]
# Final Evaluation Result

## From BIGRR Side

As we can see on this milestone's end date, it is November 11. And users have already started using the feature.

![Image](https://github.com/user-attachments/assets/45b24260-de1f-4255-84b4-258b9ecbed28)

And it's also represents on Booking Calendar in BIGRR Website

![Image](https://github.com/user-attachments/assets/c12eab8d-fa77-403e-bc5b-919a7c0b686d)

![Image](https://github.com/user-attachments/assets/06eacdd3-a9be-43fd-a022-e36ed45847cc)

Although the blocking system works well, but the messages feature doesn't use by users yet

The others result:
- Now, user (community manager) able to add maintenance event directly via BIGRR. No need to request engineering team to input those data anymore
- User (community manager) also able to start conversation with partner with specific topic about maintenance event via BIGRR
- User (community manager) able to view details about blocking event (maintenance or personal)

## From BVGO Side

### Blocking event view in BVGO
  
  ![Image](https://github.com/user-attachments/assets/1d140d01-d58c-4a36-b118-85c2d0119ef8)
  
  ![Image](https://github.com/user-attachments/assets/64250622-5559-4020-8d21-fea4aa93c439)
  
  ![Image](https://github.com/user-attachments/assets/9c72f322-34c4-4492-94e7-5797601248fe)

### Add new block event

  ![Image](https://github.com/user-attachments/assets/4f4d915f-d99c-4fe6-877f-bda58069758b)

## SLA Status

- Ensure 100% functionality of attaching text details and images to the maintenance block with no errors during usage ✅
    - from 10 logs, all of those show there is no error to show text details and images to maintenance block
- Ensure 100% functionality of the communication feature through the maintenance block without error ✅
    - from 2 logs of conversation, there is no error about it. but, the conversation has been deleted due to condition update from partner
- Ensure 100% accuracy in fetching and visualizing detailed information behind personal use blocks for the internal team without errors ✅
    - from 17 logs, all of those show there is no error to show detailed information of behind personal information

## Conclusion

Based on evaluation result above, we announce that this milestone is SUCCESS!

## Room of Improvement

Maybe, we could make it in one standard title writing in database for both personal use and maintenance use

![Image](https://github.com/user-attachments/assets/63821c60-beef-45a9-bf08-c05ae798073c)

**Comment by Vidiskiu** [comment]
Overall Point: 5.5
Functional Complexity: 1.75

> The improvements in flexibility and communication for the calendar blocking process involve multiple user flows and decision points, with new detailed blocking options for internal employees and partners.

Technical Complexity: 1.5

> Technical complexity is moderate as the enhancement involves backend changes to support additional data (text, images) and new categorization options, as well as frontend changes for UI to input and display this information.

UI/UX Complexity and Impact: 1.25

> Significant UI/UX design work is needed to ensure user-friendly experience in attaching details to blocks and category selection for partners, as well as visualizing this detailed information efficiently for internal employees.

Testing and Quality Assurance: 1

> Extensive testing is required to validate the functionality of new features including attachments, categorizations, and communication features ensuring SLA metrics such as 100% functionality and accuracy.

Risk and Dependencies: 0

> Risks and dependencies are not explicitly mentioned, assuming typical product development dependencies and risks are manageable within team capabilities.
