### ISSUE TITLE
#2 Iteration: Badge - Ranking and Leaderboard for Partner Digital Token of Achievements

### ISSUE THREAD

**Issue by krisnaBukitVista** [Bukit-Vista/roadmap#74]
# Description 
This iteration focuses on introducing a monthly evaluation and league placement system for properties on BVGO. Partners will be placed into one of five leagues—Diamond, Platinum, Gold, Silver, or Bronze—based on their performance. A digital badge representing their league placement will be displayed on their BVGO dashboard, motivating them to engage more actively and improve their performance.

![Image](https://github.com/user-attachments/assets/edfe1fac-e8be-4925-ac03-90c173c81cc8)

# Problem 
- Increase app stickiness: By adding this feature, we aim to give partners another reason to open and use the BVGO app regularly.
- Encourage performance improvement: Partners should be incentivized to continuously strive for better performance compared to the previous month.

# Solution 

## Basic Requirements
- Five Leagues: Partners will be placed in one of the following leagues based on performance: Diamond, Platinum, Gold, Silver, or Bronze.
- Badge Integration: A badge representing their current league will be integrated on the BVGO dashboard.
- Leaderboard Visibility: Partners will not have access to the leaderboard, ensuring they focus on personal performance rather than comparing with others.
- Visible Information: Partners will only be able to view their badge, overall rating, occupancy rate, and current score.
- Superhost Profile Management: Indicate whether the property is managed by a superhost profile.

## Evaluation Method
- Performance Metrics: The evaluation will be based on two key metrics—occupancy rate and overall rating.
- Consistency with Previous Iteration: The normalization scale and weight from the first iteration will be retained for consistency.
- Daily Performance Calculation: The system will calculate partner performance daily.

## Mapping to League
- Diamond: Score 10
- Platinum: Score 9
- Gold: Score 8
- Silver: Score 7
- Bronze: Score below 7

## Notification System
- Notifications will be sent out twice during each cycle:
When a partner’s league changes due to an upgrade or downgrade.
- After the monthly evaluation has been completed, informing them of their final league placement.

# Measurement Metrics
- The badge feature is fully integrated and operational on BVGO.
- Accurate assignment of badges, ensuring they reflect the correct partner achievements based on the defined metrics and criteria.

# SLA
- The badge feature must function without any errors or malfunctions on the partner’s dashboard.
- League badges must accurately and consistently reflect partner achievements, adhering to the pre-defined performance criteria and evaluation process.

**Comment by katibpasha** [comment]
## Final Evaluation

We've successfully released new BVGO version 2.16.2 to Appstore and Playstore. Then, we also implemented 10 whitelisted properties for this new property league feature. Here is the whitelisted properties:
- serenity villa
- kencana
- zumera
- maharaja residence
- sunny
- kembang kuning
- zen den
- amazon guesthouse
- mango sky and marlex
- sage sun

### Functionality Check

The property league card now display the property's name, occupancy rate, overall rating score, property's image, and badge.
![Image](https://github.com/user-attachments/assets/bf02df89-97a2-465d-bc60-422b7eac3af0)

### Accuracy Check

The feature has reflect league changes, and also show the number correctly. For example in Amazon GH,
![Image](https://github.com/user-attachments/assets/d585eb77-a839-4646-952b-a859e33897fe)

Then, in the card shows 91,94% of occupancy rate

### Conclusion

Finally, based on evaluation result above I could say that we achieved this milestone's SLA!

### Room of Improvement
- We can adjust the decimal number behind comma for overall rating score to be tidier by limit it for max. 2 numbers
