### ISSUE TITLE
Redesign of the Community Expert Card for Improved User Experience

### ISSUE THREAD

**Issue by krisnaBukitVista** [Bukit-Vista/roadmap#79]
# Description 
This project aims to enhance the user experience on the community expert page by addressing design, functionality, and usability issues. Specifically, the project will focus on redesigning the card layout to handle long text more aesthetically, adding label tags to cards, and introducing a "Contact Us" button to streamline communication.

![Image](https://github.com/user-attachments/assets/275d34e7-daa2-45ae-b28a-a469b3709216)

figma design: https://www.figma.com/design/BA6pFQ89q1YZbzgzyYKLm3/Work---Bukit-Vista-1?node-id=419-2&t=IjPumgvAhIpu4d2Z-1

# Problem 
- Card Design:
The current card design on the community expert page is not visually appealing. Long blocks of text make it difficult to read and detract from the user experience.
- Missing Tags:
There are no tags associated with the cards, making it harder to categorize or filter content efficiently.
- Lack of "Contact Us" Button:
Users do not have a direct way to get in touch with community experts or support, as there is no "Contact Us" button on the page.

# Solution 
- Redesign Card Layout:
Improve the aesthetic of the card design by optimizing the layout for long text, making it more visually engaging and readable.

- Add Editable keywords:
Introduce editable lkeyword label for each card, allowing for better categorization. 

- Implement a "Contact Us" Button:
Add a prominent, functional "Contact Us" button to each card or the page itself to allow easy communication between users and community experts.

# Measurement Metrics
- Average Engagement Time per Active User – Measures how much time an active user spends engaging with the platform.
- Average Session Duration – Tracks the duration of each session to gauge user engagement in a single visit.
- Bounce Rate – Indicates the percentage of users who leave the platform after a single interaction, helping identify areas for engagement improvement.

# SLA
- 10% increase in average engagement time per active user.
- 10% increase in average session duration.
- 10% decrease in bounce rate.

# Evaluation 
## Revision
We received a minor revision request from the user to change the text opacity from 50% to 100%. There has been no feedback from BCA, so we are clear to proceed with obtaining the user's final approval.

## SLA Metrics:
- Average Engagement Time per Active User: Before implementation, the average engagement time was 47 seconds. After implementation, it has increased to 1 minute and 24 seconds, representing an 85.28% increase.
- Average Session Duration: Previously, the average session duration was 4 minutes and 3 seconds. It has now increased to 4 minutes and 58 seconds, achieving a 40.7% increase.
- Bounce Rate: Initially, the bounce rate was 11.76%. It has now decreased to 7.14%, resulting in a -39.29% decrease.

These metrics indicate a significant improvement in user engagement and interaction quality following the implementation.

**Comment by Vidiskiu** [comment]
@krisnaBukitVista Mid-evaluation on 2024-11-05

**Comment by krisnaBukitVista** [comment]
mid-evaluation (November 3rd)

The project successfully meets the user requirements by providing the necessary functionalities and features as requested. After testing:

- Functionality: The "Visit" and "Contact Us" buttons are functioning perfectly without any issues. They lead to the intended actions and enhance user engagement by providing easy access for user interaction.
- Keyword Tags: I tested the add and remove functions for keyword tags, and they are working smoothly. The system allows for easy management of keywords, which contributes to better content organization and visibility.

Design Quality: While the design has been delivered and is functional, I am uncertain about its visual appeal. I will consult with the user and the Business Case Analysis (BCA) team to verify whether the design meets their expectations and aligns with user experience standards.

Performance Note: I noticed that the page load time is somewhat slow. This could impact user experience, so further optimization might be necessary to ensure a smooth, responsive interface.

Overall, the project is in good shape functionally but may require additional feedback and optimizations to fully meet performance and aesthetic expectations.

**Comment by krisnaBukitVista** [comment]
For transparency final evaluation
![Image](https://github.com/user-attachments/assets/f0d80212-11b7-4095-98f8-61068901d897)

**Comment by Vidiskiu** [comment]
Overall Point: 4.25
Functional Complexity: 0.5

> Functional changes such as adding label tags and a 'Contact Us' button are relatively straightforward and only moderately affect the functional flow.

Technical Complexity: 0.5

> The technical complexity is low since adding label tags and communication buttons is typically a simple addition to existing features, but it does involve new functionality that needs to be integrated.

UI/UX Complexity and Impact: 1.25

> Significant UI/UX work is required to enhance the card layout with a keen focus on handling long texts and usability, given that there is a figma design included for guidance on the redesign.

Testing and Quality Assurance: 1

> Testing for the UI/UX redesign will be needed to ensure aesthetic appeal and usability across various screen sizes and platforms.

Risk and Dependencies: 1

> There may be some risk associated with ensuring the design scales well with the content of varying lengths and the introduction of new functional elements, such as the 'Contact Us' button.
