### ISSUE TITLE
Repurpose GAIA ECHO as Knowledge Manager

### ISSUE THREAD

**Issue by krisnaBukitVista** [Bukit-Vista/roadmap#82]
# Description 
In our ongoing mission to propel Bukit Vista to the top 1% ranking in the market, we are embarking on a new adventure to strengthen our bond with partners. Picture the ECHO platform as our latest tool in the arsenal utilized by our sidekick, Intelligence, originally forged for the heroic efforts of Business Development (BD). We are now adapting it to bolster the efforts in Client Management (CM). The aim is to transform ECHO into a structured system for logging and feedback that meticulously chronicles our epic conversations with partners and extracts vital insights. With each dialogue, ECHO acts as a scribe, capturing details and unearthing sentiments, all securely archived in our fortress, HubSpot. This empowers our team of heroes – ENG, MKT, OPS, and Intelligence – to revisit these sagas, ensuring that our progress in solidifying partner relations is steadfast and never faltering.

# Problem 
- The Nemesis of Disorganized Dialogue: In our quest to outmaneuver the non-Bukit Vista entities vying for our guests, our journey is hampered by a lack of a centralized, trustworthy repository for conversation logs. Our heroic teams face a chasm, unable to revisit the annals of past discussions or wield insights efficiently.
- The Gap of Untracked Progress: The absence of a structured system to monitor the flow of conversations with partners presents a vexing challenge. Without such a beacon, understanding the tapestry of past dialogues becomes elusive, resulting in missed follow-ups, fractured communication, and potential "death scenes" where partners are swayed by those comparing our pivotal decisions unfavorably against outsider whispers, or owners making risky choices without owning the consequences in coordination settings like pricing or descriptions.

# Solution 
- Repurpose Gaia-ECHO: The existing Gaia-ECHO platform will be repurposed for Client Management (CM) in addition to Business Development (BD), ensuring all teams can benefit from centralized conversation tracking.
- Modular ECHO System: ECHO will be made modular, allowing it to be connected with any conversation-based agent or platform.
- ECHO as a Filter for Knowledge: In addition to logging conversations and tracking feedback, ECHO will act as a filter for important knowledge worth storing. Any key information or insights deemed valuable will be transferred to Chroma, making it easily retrievable via the #ask-anything channel. This ensures that critical knowledge is not only stored but also accessible for future reference and decision-making.

# Measurement Metrics
- Functionality:
  - Ensure ECHO can forward the literal conversation, summary, and sentiment analysis to HubSpot automatically.
  - Verify the correct storage of data within the appropriate partner profiles in HubSpot.
  - Measure the accuracy of ECHO's ability to filter important knowledge worth storing

# SLA
- Knowledge filtering: Measure the accuracy of ECHO's ability to filter important knowledge worth storing, with at least 90% of identified information marked as valuable by users.

**Comment by Vidiskiu** [comment]
- If Ardy needs handover, Ardy -> Ali, Ali -> Robin for BVGO Backend
- Titan to followup progress and see results so far with Ardy

**Comment by katibpasha** [comment]
## Final Evaluation

For testing and evaluation purpose, I took some sample of partners:
- Yetty Kunh - Casa Kirala
    - Conversation Dec 19 2024
        ![Image](https://github.com/user-attachments/assets/1976d7c7-4094-4215-8675-4dd13ae3ab97)
        ![Image](https://github.com/user-attachments/assets/a1f458ee-e7d3-4b65-8dd5-794a2c7a8dff)

    - Echo Summary
        ![Image](https://github.com/user-attachments/assets/1b2e998b-1c60-4ffc-b719-a562408dd4cd)

- Bli Cahya - Kubu Kembar Guesthouse
    - Conversation Dec 19 2024
        ![Image](https://github.com/user-attachments/assets/edf265cd-3c53-4fde-aaf4-f5bae74d3fa9)
        ![Image](https://github.com/user-attachments/assets/491bdbca-22b6-4b7f-ad9d-b613811fb774)
        ![Image](https://github.com/user-attachments/assets/41a12c5f-cc4f-4747-af81-b7efbe9f97f4)

    - Echo Summary
        ![Image](https://github.com/user-attachments/assets/e9eeb9e5-e722-4519-865f-99788f4b6ec8)


- Alessandro Pacciani - The Black Rock Villa 01
    - Conversation Dec 19 2024
        ![Image](https://github.com/user-attachments/assets/0978c247-e5d1-4837-8b69-e431ef304915)
        ![Image](https://github.com/user-attachments/assets/f241e716-30c9-4e3f-b785-525d763effef)
        ![Image](https://github.com/user-attachments/assets/a5aed0b1-8bb8-4037-876c-47228ff918de)
        ![Image](https://github.com/user-attachments/assets/d38492f4-975b-48fd-9b6f-ad090f5c9da0)


    - Echo Summary
        ![Image](https://github.com/user-attachments/assets/f625c677-898e-4f51-93e3-ef765623d1af)

### Conclude

From the attached result of three partners, all looks working well. Echo able to summarize and its emotion, sentiment, and unspoken insight of the entire conversation on specific date. But, if you see on Kubu Kembar Guesthouse conversation, the emotion looks slightly mis-detection. I think it caused by the conversation is full of Dela's messages so Echo retrieve the insight full from Dela's side

**Comment by Vidiskiu** [comment]
Overall Point: 5.5
Functional Complexity: 1.5

> Enhancing ECHO with a conversation tracking and feedback system for CM involves a significant update to existing functionality, with new decision points on how to handle different types of dialogues and insights extraction.

Technical Complexity: 2

> The technical effort includes integrating with HubSpot, creating a modular system that can connect with different conversation agents, and developing an algorithm for sentiment analysis and knowledge filtering, which are advanced technical tasks.

UI/UX Complexity and Impact: 0.5

> UI modifications might be minor, mainly focused on displaying new features for ECHO on the existing platforms without significant visual or interactive overhauls.

Testing and Quality Assurance: 1

> Testing for the repurposed ECHO includes verifying accurate data forwarding and storage in HubSpot, as well as the precision of knowledge filtering and sentiment analysis, which requires a comprehensive testing strategy.

Risk and Dependencies: 0.5

> There is a moderate risk due to the integration with HubSpot and the dependency on the accuracy of the sentiment analysis and knowledge filtering algorithms. However, it is mitigated by an SLA targeting 90% accuracy.
