### ISSUE TITLE
User Profile Improvement for BVGO

### ISSUE THREAD

**Issue by krisnaBukitVista** [Bukit-Vista/roadmap#83]
# Description 
This project aims to enhance the user experience by improving the profile information display, integrating real-time user statistics, and introducing profile completion alerts. Users will be able to easily view and edit their profile details, including guest statistics, review ratings, and hosting experience, with streamlined navigation and functionality.

# Problem 
- Users currently lack visibility into key profile information, such as their superhost status, personal details, and hosting statistics, leading to a suboptimal user experience.
- There is no alert system notifying users when their profile information is incomplete, potentially affecting user engagement and trust.
- Editing profile information is not intuitive or well-supported, hindering users' ability to maintain up-to-date and accurate details.

# Solution 
- General Profile Information Display: Implement a complete profile view with labels like 'Superhost,' full name, occupation, and address.
- User Statistics Section: Display user statistics (number of guests hosted, average review score, and hosting experiences) in real-time on the Menu page.
- Profile Completion Alert: Introduce an alert block notifying users of incomplete profile information, accompanied by an 'edit profile' button and a default image for missing profile photos.
- Edit Profile Information Functionality: Allow users to seamlessly edit their personal information, with intuitive navigation to the Personal Information edit page and a responsive loading animation during profile updates.

# Measurement Metrics
- Real-Time Data Updates: Monitor the accuracy and speed of real-time updates to guest, review, and experience statistics.
- User Feedback: Gather qualitative feedback through surveys and interviews to assess user satisfaction post-implementation.

# SLA
- Edit Profile Functionality: Users should be able to edit and save their personal information with successful redirection of clicking 'edit profile.'
- User feedback: Gather 75% positive review from user sampling

**Comment by katibpasha** [comment]
# Final Evaluation Result

## Evaluation Based on SLA
- Edit Profile Functionality: Users should be able to edit and save their personal information with successful redirection of clicking 'edit profile.'
  - General Profile Information Display: 'Superhost' label, full name, occupation, and address

    https://bukitvista.slack.com/files/U078S3YGV6H/F080Y9S7PBP/screenrecorder-2024-11-15-16-54-54-594.mp4
  - User Statistics Section: Display user statistics (number of guests hosted, average review score, and hosting experiences) in real-time on the Menu page

    https://bukitvista.slack.com/files/U078S3YGV6H/F0813589D7E/screenrecorder-2024-11-15-14-58-02-489.mp4
  - Profile Completion Alert

    https://bukitvista.slack.com/files/U078S3YGV6H/F080L6LJKB9/screenrecorder-2024-11-15-15-17-10-192.mp4
  - Allow users to seamlessly edit their personal information, with intuitive navigation to the Personal Information edit page and a responsive loading animation during profile updates

    https://bukitvista.slack.com/files/U078S3YGV6H/F080L3TJ3L7/screenrecorder-2024-11-15-14-56-47-585.mp4
- User feedback: Gather 75% positive review from user sampling

**Comment by Vidiskiu** [comment]
Track user engagement and behavior through updates of profile picture and profile description.

**Comment by Vidiskiu** [comment]
Overall Point: 5.5
Functional Complexity: 1.5

> This enhancement involves moderate functional complexity to implement real-time statistics, profile completion alerts, and intuitive edit features.

Technical Complexity: 1.5

> Technical effort is moderate as it requires real-time data fetching, updating the user profile system, and improving navigation.

UI/UX Complexity and Impact: 0.75

> UI/UX updates, including a new alert block and improved navigation for editing profile information, will have a moderate impact on user experience.

Testing and Quality Assurance: 1

> A moderate level of testing for real-time data updates and functionality of profile editing is required to ensure robustness and reliability.

Risk and Dependencies: 0.75

> There's a moderate risk due to the complexity of implementing real-time updates and integration with current user data, along with dependencies on accurate and timely data processing.
