### ISSUE TITLE
UI Improvement on About Us Page

### ISSUE THREAD

**Issue by RezaConz** [Bukit-Vista/roadmap#85]
# Description
The "About Us" page contains a significant amount of content that is displayed in an unorganized manner. This affects the overall visual hierarchy and interferes with user comfort when browsing the website.
![Image](https://github.com/user-attachments/assets/ed6d4027-aaf3-4e40-8456-e12eb1e1842e)

# Problem
The current layout of the "About Us" page lacks structure and a clear flow of information, which may reduce the effectiveness of the message and lead to user frustration.

# Solution
Redesign the page with a clean layout, focusing on improving user experience by structuring the content more effectively. Implement sections with concise headings, visual cues, and an organized content hierarchy that mirrors best practices for information delivery.

# Measurement metrics
- User Approval 
- Increase average engagement time per active user
- Increase average session duration

# SLA
- Got approval from user 
- Increase average engagement time per active user by 10% after 1 week of implementation 
- Increase average session duration by 10% after 1 week of implementation 

# Evaluation

## Mid-Evaluation Results:
- Average Engagement Time per Active User:
  - Previous: 13 seconds
  - Current: 1 minute 3 seconds
  - Improvement: 365% increase, indicating a significant enhancement in user engagement.
  
- Average Session Duration:
  - Previous: 36 seconds
  - Current: 4 minutes 1 second
  - Improvement: 559% increase, reflecting a substantial positive impact on session quality.

## Final Evaluation Results:
- Average Engagement Time per Active User:
  - Previous: 52 seconds
  - Current: 50 seconds
  - Outcome: Slight decrease, indicating that the SLA for this metric has not been met.

- Average Session Duration:
  - Previous: 2 minutes 8 seconds
  - Current: 2 minutes 37 seconds
  - Outcome: Consistent increase, showing sustained improvement in session duration.

Conclusion: While the project has demonstrated continuous improvement in average session duration, the final evaluation shows that it did not fully meet the SLA due to a decrease in the average engagement time per active user. 

Attachment
Reference design:
https://www.vidyard.com/about/

**Comment by krisnaBukitVista** [comment]
# Mid Evaluation (Nov 11th)

## Approval and Feedback:
The user has provided full approval for the current design implementation, with no additional revisions requested. The user also noted that the current design is an improvement over the previous version, enhancing both functionality and user experience.

![Image](https://github.com/user-attachments/assets/739545b1-3538-4156-ba87-9d1c9aaf9f0b)
![Image](https://github.com/user-attachments/assets/872a8bb4-341b-40f8-860e-233f22a6f18f)

## SLA Performance Metrics:

- Average Engagement Time per Active User:
  - Previous: 13 seconds
  - Current: 1 minute 3 seconds
  - Improvement: 365% increase, indicating a significant enhancement in user engagement.

- Average Session Duration:
  - Previous: 36 seconds
  - Current: 4 minutes 1 second
  - Improvement: 559% increase, reflecting a substantial positive impact on session quality.

- Bounce Rate:
  - Previous: 14.29%
  - Current: 22.22%
  - Change: 55.56% increase.

While the bounce rate has risen, there is still a week left in the evaluation period to assess if further improvements can help reduce it.

Overall, the project has demonstrated considerable success in improving engagement metrics, with ongoing monitoring planned for the bounce rate over the next week.

![Image](https://github.com/user-attachments/assets/353773b1-b5fc-48d3-bf02-e1d8a68ff627)

**Comment by Vidiskiu** [comment]
Overall Point: 3.75
Functional Complexity: 0

> As this is a UI improvement issue, there is no functional complexity involved in terms of back-end logic or new feature development.

Technical Complexity: 0.5

> Improvements to the 'About Us' page will likely involve only front-end changes, with no significant technical complexity or integration with systems or APIs.

UI/UX Complexity and Impact: 1.25

> The task involves a full redesign for better structure, clearer information flow, and improved visual hierarchy, which is a significant overhaul of the UI/UX with a noticeable impact on the overall user experience.

Testing and Quality Assurance: 1.25

> Due to the fundamental changes in the layout, comprehensive testing is needed to ensure the redesign enhances user engagement metrics as targeted, with cross-browser and cross-device functionality confirmed.

Risk and Dependencies: 0.75

> While primarily a front-end change, there's a moderate risk associated with not achieving the desired improvement in user engagement metrics, as reflected in the mixed SLA evaluation results.
