### ISSUE TITLE
AUM / Analyze unspoken question from fireflies

### ISSUE THREAD

**Issue by bstiawan** [Bukit-Vista/roadmap#9]
# Description: 
BD has requested automation for fireflies on Vacaroo and Google Meet platforms. In response, we're delving into unspoken queries to understand their needs better. By analyzing these nuances, we aim to match their requirements with relevant marketing articles, providing tailored solutions for BD's objectives.

# Problem:
- Answering similar questions repeatedly
- We need content idea to write article

# Solution:
- Write article for frequently asked questions
- Send link to article when question is asked

# Measurement metrics:
- amount of conversation being analyzed
- satisfaction score

# SLA 
- 100% conversation being analyzed by echo 
- 80% satisfaction score from user report 

# result of evaluation 
- you can check it on the link [here](https://docs.google.com/spreadsheets/d/1oeU1MXrzAMFQFU0-XCeCUo6_YIV0xHCciU-jS-eO8xk/edit#gid=0)
- 100% conversation being analyzed by echo 
- 40% satisfaction score from user report 

# Analysis of the issue
- Giving feedback to client instead of BD
- Original answer on the full conversation and on the table is different
- Need to add CTA as a feedback in conversation 

# Next action 
- we solve all problem listed in the analysis above as second iteration

**Comment by krisnaBukitVista** [comment]
Current update (April 30th): 
user did not completed the report, the latest deadline expected on May 3rd

**Comment by Vidiskiu** [comment]
Overall Point: 5.4

Functional Complexity: 0.9

> Automatic analysis of unspoken questions involves understanding conversational context and nuances, which adds to functional complexity.

Technical Complexity: 1.2

> Integrating analysis with Vacaroo and Google Meet platforms and automating the retrieval and processing of conversational data is highly technical.

UI/UX Complexity: 0.3

> The UI/UX component seems less complex as the main emphasis is on backend data handling and analysis.

Data Manipulation: 0.9

> Parsing and interpreting conversational data requires advanced data manipulation, but established natural language processing techniques mitigate this somewhat.

Testing: 0.4

> Testing for accuracy in the context of natural language understanding is crucial but based on tangible criteria and metrics.

Dependencies: 0.4

> Depends on external APIs for Vacaroo and Google Meet, as well as possible natural language processing libraries.

Risk and Uncertainty: 0.4

> There is the uncertainty involved in how well the system will interpret unspoken queries, but the use of a satisfaction score informs iterations.

User Impact: 0.9

> Improving the efficiency of answering queries has a significant positive impact on user satisfaction.
