### ISSUE TITLE
Backend Migration to Jakarta Server

### ISSUE THREAD

**Issue by krisnaBukitVista** [Bukit-Vista/roadmap#91]
# Description 
The objective of this project is to migrate the backend of our web application, currently hosted on AWS EC2 in Ohio, to a Jakarta-based server. The frontend will remain hosted in Singapore. This backend migration aims to enhance connectivity and performance for Indonesian users by leveraging local peering agreements and reducing latency.

# Problem 
Users are experiencing issues reaching the backend due to the geographical distance between the backend (Ohio) and the target user base (Indonesia). Hosting the backend in Jakarta will help reduce latency, improve connectivity, and increase reliability by bypassing international routing paths.

# Solution 
## Migrate the backend 
Migrate to AWS servers in Jakarta to improve connection stability and latency for local users.

## Adjust infrastructure components related to the backend:
- VPC and ELB configurations tailored for the Jakarta region.
- EC2 Server, Launch Template, and Auto-scaling settings updated for optimal performance in Jakarta.
- Load Balancer settings to manage traffic efficiently within the new region.
- CodePipeline Deployment adjustments to ensure successful backend deployment to Jakarta.
- Parameter Store and Environment Variables updated to support Jakarta-based operations.
- Route53 Domain configurations updated to direct traffic to the new backend location.

This approach will optimize backend connectivity while maintaining the front-end location.

# Measurement metrics
- Latency Reduction: Reduction in backend response time for Indonesian users.
- Connection Stability: Improved success rate of backend requests from Indonesian ISPs.

# SLA
- Latency Reduction: Achieve at least a 30% reduction in backend latency for Indonesian users within 1 week post-migration.
- Uptime: Ensure 99.9% uptime during and after the migration process.
- Reliability Increase: Attain a 20% increase in successful backend connection rates for Indonesian users.

**Comment by RobinNusantara** [comment]
Percentile | Metric (Pre-Migration) | Metric (Post-Migration) | Improvement (%) | Observations
-- | -- | -- | -- | --
p50 | 26ms | 7.33ms | 71.8% faster | Significant reduction in median query time.
p75 | 234ms | 59ms | 74.8% faster | Noticeable improvement in query response at the 75th percentile.
p90 | 994ms | 299ms | 69.9% faster | Performance remains consistent as we move to higher percentiles.
p95 | 1,927ms | 678ms | 64.8% faster | Similar trend as the p90, showing consistent optimization.
p99 | 6,249ms | 2,634ms | 57.9% faster | Considerable performance improvement in edge cases.
p99.9 | 28,104ms | 12,679ms | 54.9% faster | Improved performance even for the most extreme cases.
Max | 47,696ms | 18,458ms | 61.3% faster | Maximum query response time has been drastically reduced.

<hr><h3><strong>Observations</strong></h3><ol><li><strong>Median (p50) Improvement</strong>: Post-migration, the median query time improved by ~72%, reflecting better average query performance.</li><li><strong>Higher Percentiles</strong>: Performance gains decrease slightly at higher percentiles (p99, p99.9), but all improvements remain above 50%.</li><li><strong>Maximum Query Time</strong>: The maximum query response time dropped from 47.7 seconds to 18.5 seconds, showing significant stabilization in worst-case scenarios.</li></ol><hr><h3><strong>Conclusions</strong></h3><ul><li>The migration resulted in substantial performance gains across all percentiles.</li><li>Median queries (p50-p75) saw the most dramatic improvements, making user experience significantly better.</li><li>High-latency outliers (p99 and above) were also improved, though there’s still room for further optimization in extreme cases.</li></ul>

**Comment by RobinNusantara** [comment]
On average, the performance of endpoints has improved by 50-80%. This is based on the first 18 endpoints sorted by average response time. Any endpoint with an average response time above 2 seconds needs to be enhanced immediately, whether through database query optimization, indexing, or code improvements.

**Comment by RobinNusantara** [comment]
To maximize performance improvements for the backend application bigrr-be, which powers the BigRR/BVGO APIs, adopting Bun.js could be a game-changer. Based on the data I’ve reviewed, Bun.js offers significantly better runtime performance compared to Node.js, delivering much more efficient results. By leveraging Bun.js, we can achieve optimal backend application performance and enhance the user experience even further.

**Comment by RobinNusantara** [comment]
Here are the endpoints with an average response time greater than 2 seconds when fetched. These endpoints need to be refactored. My suggestion is that we immediately prepare a future project to improve the performance of our application.

| Resource Endpoint                     | Service  | Average Duration (ms) | Min Duration (ms) | Max Duration (ms) |
|---------------------------------------|----------|-----------------------|-------------------|-------------------|
| GET /v1/xlsx/accounting-reports      | bigrr-be | 4706.0                | 1062.1            | 17590.0           |
| GET /v1/transactions                  | bigrr-be | 4489.0                | 22.0              | 29000.0           |
| GET /v1/newsletters                   | bigrr-be | 4462.0                | 1294.2            | 86480.0           |
| GET /v1/profiles                      | bigrr-be | 4343.0                | 16.8              | 91050.0           |
| GET /v1/properties/:id/payouts        | bigrr-be | 3906.0                | 24.2              | 29000.0           |

**Comment by RobinNusantara** [comment]
Those endpoints are all used in BVGO, so if they become faster and can be completed in less than 2 seconds, I believe BVGO will become much more stable.

**Comment by Vidiskiu** [comment]
Overall Point: 5
Functional Complexity: 1

> The functional aspect involves migrating existing configurations to a new region, which is a moderate complexity task that does not require creating new functionalities or logic.

Technical Complexity: 1.75

> The project requires comprehensive knowledge of AWS services, including VPC, ELB, EC2, and Route53 as well as fine-tuning for the Jakarta region, introducing moderate to high technical complexity.

UI/UX Complexity and Impact: 0

> The migration does not involve any UI/UX changes as the front-end hosting remains in Singapore.

Testing and Quality Assurance: 1

> Testing involves ensuring the configurations operate as intended in the new region, with a focus on performance metrics like latency reduction and connectivity stability, making it a moderate testing effort.

Risk and Dependencies: 1.25

> There is a high risk due to the potential impact of migration on service availability, and this is coupled with strict SLA requirements for latency and uptime, making the move to a new region a high-risk endeavor.

**Comment by Vidiskiu** [comment]
- Concluded the Milestone
- Created backlog [Refactor High-Latency Endpoints for BigRR-BE Services](https://github.com/orgs/Bukit-Vista/projects/1/views/1?pane=issue&itemId=91971692&issue=Bukit-Vista%7Cbigrr-be%7C3525)
