### ISSUE TITLE
Improving Google Colab Visualization Output for Ratings Analysis

### ISSUE THREAD

**Issue by krisnaBukitVista** [Bukit-Vista/roadmap#95]
# Description 
The purpose of this project is to enhance the current visualization output in Google Colab for analyzing various rating components. Currently, the output is visualized as a scatter plot, which has limitations in displaying dense data points. This project aims to replace the scatter plot with a hexbin plot for better clarity, particularly in areas of high data density. Additionally, the new visualization will allow for component-wise analysis of different rating categories, providing more insightful and visually organized data representations.

# Problem 
The current scatter plot visualization method in Google Colab does not effectively handle dense datasets. When data points overlap, the scatter plot becomes cluttered, making it difficult to interpret trends accurately. This issue affects the ability to analyze and communicate insights from the data, especially in the context of high-volume ratings data. Additionally, the existing visualization does not provide component-wise breakdowns, making it challenging to focus on individual rating dimensions (such as cleanliness, communication, etc.).

# Solution 
To address these challenges, this project will implement the following improvements:
- Switch to Hexbin Plot: Replace the current scatter plot with a hexbin plot, which can more effectively display dense areas by aggregating data into hexagonal bins. This approach will reduce visual clutter and improve interpretability.
- Component-wise Visualization: Enable separate visualizations for each rating component, including:
  - Overall Rating
  - Accuracy Rating
  - Cleanliness Rating
  - Value Rating
  - Communication Rating
  - Check-in Rating
- Color Coding for Density: Use a color gradient to indicate density within each hexbin, allowing users to easily identify areas of higher ratings concentration.
- Documentation and Instructions: Provide documentation for users on how to interpret hexbin plots for each rating component, ensuring that the visualization enhancements are intuitive and accessible.

# Measurement metrics 
- Functionality: Ensure Google Colab successfully runs without errors and accurately displays data in hexbin format.
- Data Accuracy: Confirm that the hexbin plot accurately reflects the data values for all rating components (Overall Rating, Accuracy, Cleanliness, Value, Communication, Check-in).
- Component-wise Visualization: Verify that separate hexbin plots can be generated for each rating component without issues.

# SLA
- Google Colab Execution: Google Colab must run without any errors during the execution of hexbin plot generation.
- Accurate Hexbin Data Representation: The hexbin plot must accurately depict the underlying data, reflecting true values for each rating component. 
- Component-specific Visualization: Users must be able to generate separate hexbin plots for each individual rating component—Overall Rating, Accuracy, Cleanliness, Value, Communication, and Check-in

**Comment by krisnaBukitVista** [comment]
current google collab: 
https://colab.research.google.com/drive/1R3C0ILpIyVw5apZ6D3pwuDgsn8obKwJO#scrollTo=5Cr5skml8wE2

**Comment by Vidiskiu** [comment]
Overall Point: 5.25
Functional Complexity: 1.5

> The enhancement involves a moderate increase in functional complexity with the introduction of component-wise analysis, which adds multiple flow paths for generating specific visualizations.

Technical Complexity: 1.5

> While replacing the visualization technique is a moderate task, ensuring accuracy and stability across different data sets introduces a fair amount of technical effort and complexity.

UI/UX Complexity and Impact: 0.75

> The change from a scatter plot to a hexbin plot represents a moderate UI/UX update. The requirement for color coding and clear documentation for users implies a substantial UX consideration.

Testing and Quality Assurance: 1

> Testing for this feature involves verifying the accuracy of the hexbin visualizations and ensuring that separate plots for different rating components function correctly. It requires a thorough testing approach but does not necessitate extensive cross-platform testing or complex scenarios.

Risk and Dependencies: 0.5

> The risk and dependencies for this enhancement are relatively low, as it hinges primarily on internal data visualization updates without a heavy reliance on external APIs or services.

**Comment by krisnaBukitVista** [comment]
User approval
![Image](https://github.com/user-attachments/assets/f2b96ad7-d1bc-46b6-9f1a-8c0c6469b68a)

**Comment by krisnaBukitVista** [comment]
# Visualization for individual rating component 

## Overall Rating
![Image](https://github.com/user-attachments/assets/b0094e46-f3a3-4ea2-b04c-245acd49e70d)

## Accuracy Rating
![Image](https://github.com/user-attachments/assets/65427a2a-1f9a-4024-8131-da22c31c7b55)

## Check-in Rating
![Image](https://github.com/user-attachments/assets/6e8cc4ab-8188-425c-9307-0cab519b7cd4)

## Cleanliness Rating
![Image](https://github.com/user-attachments/assets/b8837742-6dc6-4476-af62-70b75063378b)

## Communication Rating
![Image](https://github.com/user-attachments/assets/5c99373e-e69b-46ec-a24f-abe77dfdc5fd)

## Location Rating
![Image](https://github.com/user-attachments/assets/9d6c6e12-ccd8-4295-a74b-4e92f3624705)

## Value Rating
![Image](https://github.com/user-attachments/assets/d071595c-50c4-481d-8e20-c8444732278b)
