### ISSUE TITLE
#2 Iteration - UI Improvement on About Us Page

### ISSUE THREAD

**Issue by krisnaBukitVista** [Bukit-Vista/roadmap#96]
# Description
The second iteration focuses on enhancing the "About Us" page's UI to improve user engagement and experience. This includes making specific sections—such as the "Journey" and "Our Community" sections—dynamic. Admins should be able to easily update and publish data for these sections directly from the WordPress admin interface. Additionally, a more visually appealing design will be developed to present the "Journey" section, making it more engaging and informative.

# Problem 
Currently, the "Journey" and "Our Community" sections on the "About Us" page are static, requiring manual updates to the codebase for any content changes. This hinders timely updates, reduces flexibility, and increases maintenance overhead. Furthermore, the current design of the "Journey" section lacks visual appeal, which may lower user engagement and reduce average viewing duration on this section of the page.

# Solution
- Dynamic Content Management: Enable WordPress admin functionality to allow content updates for the "Journey" and "Our Community" sections directly from the admin page, so changes can be made quickly without code modifications.
- Redesign of the Journey Section: Develop a visually engaging design for the "Journey" section to capture user interest, enhance readability, and improve user engagement metrics.

# Measurement Metrics 
- Functionality on WordPress Page: Ensure the functionality in the WordPress admin page allows admins to:
  - Add, edit, and publish data for the "Journey" and "Our Community" sections.
  - Publish updates immediately without developer intervention.
- Average Viewing Duration: Measure the impact of UI 
improvements on user engagement by tracking:
  - Average time spent by users on the "About Us" page.

# SLA
- Dynamic Content Update Functionality: Achieve 100% operational functionality for adding, editing, and publishing data in the "Journey" and "Our Community" sections via the WordPress admin interface.
- Increased Average Viewing Duration: Aim to increase average viewing duration on the about us page by 10% within one week of the redesign's launch.

# Evaluation 
Performance Comparison
Evaluation Periods:
- Before Implementation: November 8th to 14th
- After Implementation: November 15th to 21st

Metrics Evaluated
- Average Engagement Time per Active User
  - Previously: 29 seconds
  - Currently: 43 seconds
  - Progress: +46.32%

- Average Session Duration
  - Previously: 1 minute and 53 seconds
  - Currently: 2 minutes and 47 seconds
  - Progress: +47%

![Image](https://github.com/user-attachments/assets/a0ea7a0f-bd50-4f95-bb7d-ec92851097be)

**Comment by krisnaBukitVista** [comment]
Mid-Evaluation Review

User Feedback:
During today's mid-evaluation, we received two mandatory revisions from the user presentation before we can secure their approval:

1. Mobile Responsiveness: Ensure the design is responsive for mobile view without compromising image content.
2. Dynamic Card Sizing: Ensure the size of the cards adjusts dynamically based on the text length.

Both revisions have already been documented as backlogs and are in progress.

SLA Evaluation:
Since we are only three days into the implementation, we compared the data for 3 days before (Nov 9–11) vs. 3 days after (Nov 15–17) the update:

* Average Engagement Time per Active User:
  * Previous: 59 seconds
  * After: 21 seconds
  * Change: +171.25%
* Average Session Duration:
  * Previous: 1 minute 1 second
  * After: 3 minutes 50 seconds
  * Change: +272.97%

The initial data shows significant improvement in user engagement and session duration, aligning positively with our goals. Further monitoring will ensure sustained performance.

**Comment by Vidiskiu** [comment]
Overall Point: 4.5
Functional Complexity: 1.5

> The functionality has moderate complexity with the addition of dynamic content management and implementing WordPress admin interfaces for specific sections.

Technical Complexity: 1.5

> Integrating dynamic content into the existing static site and ensuring admin capabilities requires a moderate level of technical implementation and WordPress expertise, but does not require architectural changes.

UI/UX Complexity and Impact: 1

> The task has a significant focus on UI/UX redesign, particularly for the 'Journey' section, to make it visually appealing. However, it does not indicate a complete overhaul of UI patterns, keeping it from the maximum score.

Testing and Quality Assurance: 0.5

> Testing will involve verifying the dynamic content features and the UI improvements, which are moderately complex but not extensive.

Risk and Dependencies: 

>
